// Code generated by go-swagger; DO NOT EDIT.

package internal_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// ProcessTransactionHandlerFunc turns a function with the right signature into a process transaction handler
type ProcessTransactionHandlerFunc func(ProcessTransactionParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn ProcessTransactionHandlerFunc) Handle(params ProcessTransactionParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// ProcessTransactionHandler interface for that can handle valid process transaction params
type ProcessTransactionHandler interface {
	Handle(ProcessTransactionParams, *models.User) middleware.Responder
}

// NewProcessTransaction creates a new http.Handler for the process transaction operation
func NewProcessTransaction(ctx *middleware.Context, handler ProcessTransactionHandler) *ProcessTransaction {
	return &ProcessTransaction{Context: ctx, Handler: handler}
}

/*
	ProcessTransaction swagger:route POST /payment/transaction internal processTransaction

Process payment transaction
*/
type ProcessTransaction struct {
	Context *middleware.Context
	Handler ProcessTransactionHandler
}

func (o *ProcessTransaction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewProcessTransactionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
