// Code generated by go-swagger; DO NOT EDIT.

package internal_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// ProcessTransactionOKCode is the HTTP code returned for type ProcessTransactionOK
const ProcessTransactionOKCode int = 200

/*
ProcessTransactionOK successful operation

swagger:response processTransactionOK
*/
type ProcessTransactionOK struct {

	/*
	  In: Body
	*/
	Payload *models.TransactionResponse `json:"body,omitempty"`
}

// NewProcessTransactionOK creates ProcessTransactionOK with default headers values
func NewProcessTransactionOK() *ProcessTransactionOK {

	return &ProcessTransactionOK{}
}

// WithPayload adds the payload to the process transaction o k response
func (o *ProcessTransactionOK) WithPayload(payload *models.TransactionResponse) *ProcessTransactionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the process transaction o k response
func (o *ProcessTransactionOK) SetPayload(payload *models.TransactionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProcessTransactionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProcessTransactionBadRequestCode is the HTTP code returned for type ProcessTransactionBadRequest
const ProcessTransactionBadRequestCode int = 400

/*
ProcessTransactionBadRequest Insufficient funds or invalid request

swagger:response processTransactionBadRequest
*/
type ProcessTransactionBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProcessTransactionBadRequest creates ProcessTransactionBadRequest with default headers values
func NewProcessTransactionBadRequest() *ProcessTransactionBadRequest {

	return &ProcessTransactionBadRequest{}
}

// WithPayload adds the payload to the process transaction bad request response
func (o *ProcessTransactionBadRequest) WithPayload(payload *models.Error) *ProcessTransactionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the process transaction bad request response
func (o *ProcessTransactionBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProcessTransactionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProcessTransactionInternalServerErrorCode is the HTTP code returned for type ProcessTransactionInternalServerError
const ProcessTransactionInternalServerErrorCode int = 500

/*
ProcessTransactionInternalServerError Internal server error

swagger:response processTransactionInternalServerError
*/
type ProcessTransactionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProcessTransactionInternalServerError creates ProcessTransactionInternalServerError with default headers values
func NewProcessTransactionInternalServerError() *ProcessTransactionInternalServerError {

	return &ProcessTransactionInternalServerError{}
}

// WithPayload adds the payload to the process transaction internal server error response
func (o *ProcessTransactionInternalServerError) WithPayload(payload *models.Error) *ProcessTransactionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the process transaction internal server error response
func (o *ProcessTransactionInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProcessTransactionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
