// Code generated by go-swagger; DO NOT EDIT.

package internal_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// ProcessRefundHandlerFunc turns a function with the right signature into a process refund handler
type ProcessRefundHandlerFunc func(ProcessRefundParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn ProcessRefundHandlerFunc) Handle(params ProcessRefundParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// ProcessRefundHandler interface for that can handle valid process refund params
type ProcessRefundHandler interface {
	Handle(ProcessRefundParams, *models.User) middleware.Responder
}

// NewProcessRefund creates a new http.Handler for the process refund operation
func NewProcessRefund(ctx *middleware.Context, handler ProcessRefundHandler) *ProcessRefund {
	return &ProcessRefund{Context: ctx, Handler: handler}
}

/*
	ProcessRefund swagger:route POST /payment/refund internal processRefund

Process refund transaction
*/
type ProcessRefund struct {
	Context *middleware.Context
	Handler ProcessRefundHandler
}

func (o *ProcessRefund) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewProcessRefundParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
