// Code generated by go-swagger; DO NOT EDIT.

package internal_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// ProcessRefundOKCode is the HTTP code returned for type ProcessRefundOK
const ProcessRefundOKCode int = 200

/*
ProcessRefundOK successful operation

swagger:response processRefundOK
*/
type ProcessRefundOK struct {

	/*
	  In: Body
	*/
	Payload *models.TransactionResponse `json:"body,omitempty"`
}

// NewProcessRefundOK creates ProcessRefundOK with default headers values
func NewProcessRefundOK() *ProcessRefundOK {

	return &ProcessRefundOK{}
}

// WithPayload adds the payload to the process refund o k response
func (o *ProcessRefundOK) WithPayload(payload *models.TransactionResponse) *ProcessRefundOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the process refund o k response
func (o *ProcessRefundOK) SetPayload(payload *models.TransactionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProcessRefundOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProcessRefundBadRequestCode is the HTTP code returned for type ProcessRefundBadRequest
const ProcessRefundBadRequestCode int = 400

/*
ProcessRefundBadRequest Invalid request

swagger:response processRefundBadRequest
*/
type ProcessRefundBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProcessRefundBadRequest creates ProcessRefundBadRequest with default headers values
func NewProcessRefundBadRequest() *ProcessRefundBadRequest {

	return &ProcessRefundBadRequest{}
}

// WithPayload adds the payload to the process refund bad request response
func (o *ProcessRefundBadRequest) WithPayload(payload *models.Error) *ProcessRefundBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the process refund bad request response
func (o *ProcessRefundBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProcessRefundBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProcessRefundInternalServerErrorCode is the HTTP code returned for type ProcessRefundInternalServerError
const ProcessRefundInternalServerErrorCode int = 500

/*
ProcessRefundInternalServerError Internal server error

swagger:response processRefundInternalServerError
*/
type ProcessRefundInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewProcessRefundInternalServerError creates ProcessRefundInternalServerError with default headers values
func NewProcessRefundInternalServerError() *ProcessRefundInternalServerError {

	return &ProcessRefundInternalServerError{}
}

// WithPayload adds the payload to the process refund internal server error response
func (o *ProcessRefundInternalServerError) WithPayload(payload *models.Error) *ProcessRefundInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the process refund internal server error response
func (o *ProcessRefundInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProcessRefundInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
