// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// CreatePromocodeOKCode is the HTTP code returned for type CreatePromocodeOK
const CreatePromocodeOKCode int = 200

/*
CreatePromocodeOK successful operation

swagger:response createPromocodeOK
*/
type CreatePromocodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.PromocodeResponse `json:"body,omitempty"`
}

// NewCreatePromocodeOK creates CreatePromocodeOK with default headers values
func NewCreatePromocodeOK() *CreatePromocodeOK {

	return &CreatePromocodeOK{}
}

// WithPayload adds the payload to the create promocode o k response
func (o *CreatePromocodeOK) WithPayload(payload *models.PromocodeResponse) *CreatePromocodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create promocode o k response
func (o *CreatePromocodeOK) SetPayload(payload *models.PromocodeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePromocodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePromocodeBadRequestCode is the HTTP code returned for type CreatePromocodeBadRequest
const CreatePromocodeBadRequestCode int = 400

/*
CreatePromocodeBadRequest Invalid request

swagger:response createPromocodeBadRequest
*/
type CreatePromocodeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePromocodeBadRequest creates CreatePromocodeBadRequest with default headers values
func NewCreatePromocodeBadRequest() *CreatePromocodeBadRequest {

	return &CreatePromocodeBadRequest{}
}

// WithPayload adds the payload to the create promocode bad request response
func (o *CreatePromocodeBadRequest) WithPayload(payload *models.Error) *CreatePromocodeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create promocode bad request response
func (o *CreatePromocodeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePromocodeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePromocodeForbiddenCode is the HTTP code returned for type CreatePromocodeForbidden
const CreatePromocodeForbiddenCode int = 403

/*
CreatePromocodeForbidden Admin access required

swagger:response createPromocodeForbidden
*/
type CreatePromocodeForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePromocodeForbidden creates CreatePromocodeForbidden with default headers values
func NewCreatePromocodeForbidden() *CreatePromocodeForbidden {

	return &CreatePromocodeForbidden{}
}

// WithPayload adds the payload to the create promocode forbidden response
func (o *CreatePromocodeForbidden) WithPayload(payload *models.Error) *CreatePromocodeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create promocode forbidden response
func (o *CreatePromocodeForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePromocodeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
