// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// CreatePromocodeHandlerFunc turns a function with the right signature into a create promocode handler
type CreatePromocodeHandlerFunc func(CreatePromocodeParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatePromocodeHandlerFunc) Handle(params CreatePromocodeParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreatePromocodeHandler interface for that can handle valid create promocode params
type CreatePromocodeHandler interface {
	Handle(CreatePromocodeParams, *models.User) middleware.Responder
}

// NewCreatePromocode creates a new http.Handler for the create promocode operation
func NewCreatePromocode(ctx *middleware.Context, handler CreatePromocodeHandler) *CreatePromocode {
	return &CreatePromocode{Context: ctx, Handler: handler}
}

/*
	CreatePromocode swagger:route POST /payment/promocode/create admin createPromocode

Create promocode with custom parameters
*/
type CreatePromocode struct {
	Context *middleware.Context
	Handler CreatePromocodeHandler
}

func (o *CreatePromocode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreatePromocodeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
