// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuthMetricsHandlerFunc turns a function with the right signature into a get auth metrics handler
type GetAuthMetricsHandlerFunc func(GetAuthMetricsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthMetricsHandlerFunc) Handle(params GetAuthMetricsParams) middleware.Responder {
	return fn(params)
}

// GetAuthMetricsHandler interface for that can handle valid get auth metrics params
type GetAuthMetricsHandler interface {
	Handle(GetAuthMetricsParams) middleware.Responder
}

// NewGetAuthMetrics creates a new http.Handler for the get auth metrics operation
func NewGetAuthMetrics(ctx *middleware.Context, handler GetAuthMetricsHandler) *GetAuthMetrics {
	return &GetAuthMetrics{Context: ctx, Handler: handler}
}

/*
	GetAuthMetrics swagger:route GET /auth/metrics getAuthMetrics

Prometheus metrics
*/
type GetAuthMetrics struct {
	Context *middleware.Context
	Handler GetAuthMetricsHandler
}

func (o *GetAuthMetrics) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthMetricsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
