// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuthGoogleLoginHandlerFunc turns a function with the right signature into a get auth google login handler
type GetAuthGoogleLoginHandlerFunc func(GetAuthGoogleLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthGoogleLoginHandlerFunc) Handle(params GetAuthGoogleLoginParams) middleware.Responder {
	return fn(params)
}

// GetAuthGoogleLoginHandler interface for that can handle valid get auth google login params
type GetAuthGoogleLoginHandler interface {
	Handle(GetAuthGoogleLoginParams) middleware.Responder
}

// NewGetAuthGoogleLogin creates a new http.Handler for the get auth google login operation
func NewGetAuthGoogleLogin(ctx *middleware.Context, handler GetAuthGoogleLoginHandler) *GetAuthGoogleLogin {
	return &GetAuthGoogleLogin{Context: ctx, Handler: handler}
}

/*
	GetAuthGoogleLogin swagger:route GET /auth/google/login getAuthGoogleLogin

Initiate Google OAuth login
*/
type GetAuthGoogleLogin struct {
	Context *middleware.Context
	Handler GetAuthGoogleLoginHandler
}

func (o *GetAuthGoogleLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthGoogleLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
