// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/auth/internal/models"
)

// GetAuthGoogleCallbackOKCode is the HTTP code returned for type GetAuthGoogleCallbackOK
const GetAuthGoogleCallbackOKCode int = 200

/*
GetAuthGoogleCallbackOK Success

swagger:response getAuthGoogleCallbackOK
*/
type GetAuthGoogleCallbackOK struct {

	/*
	  In: Body
	*/
	Payload *GetAuthGoogleCallbackOKBody `json:"body,omitempty"`
}

// NewGetAuthGoogleCallbackOK creates GetAuthGoogleCallbackOK with default headers values
func NewGetAuthGoogleCallbackOK() *GetAuthGoogleCallbackOK {

	return &GetAuthGoogleCallbackOK{}
}

// WithPayload adds the payload to the get auth google callback o k response
func (o *GetAuthGoogleCallbackOK) WithPayload(payload *GetAuthGoogleCallbackOKBody) *GetAuthGoogleCallbackOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth google callback o k response
func (o *GetAuthGoogleCallbackOK) SetPayload(payload *GetAuthGoogleCallbackOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthGoogleCallbackOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuthGoogleCallbackFoundCode is the HTTP code returned for type GetAuthGoogleCallbackFound
const GetAuthGoogleCallbackFoundCode int = 302

/*
GetAuthGoogleCallbackFound Redirect to frontend with token

swagger:response getAuthGoogleCallbackFound
*/
type GetAuthGoogleCallbackFound struct {
}

// NewGetAuthGoogleCallbackFound creates GetAuthGoogleCallbackFound with default headers values
func NewGetAuthGoogleCallbackFound() *GetAuthGoogleCallbackFound {

	return &GetAuthGoogleCallbackFound{}
}

// WriteResponse to the client
func (o *GetAuthGoogleCallbackFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// GetAuthGoogleCallbackUnauthorizedCode is the HTTP code returned for type GetAuthGoogleCallbackUnauthorized
const GetAuthGoogleCallbackUnauthorizedCode int = 401

/*
GetAuthGoogleCallbackUnauthorized Authentication failed

swagger:response getAuthGoogleCallbackUnauthorized
*/
type GetAuthGoogleCallbackUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthGoogleCallbackUnauthorized creates GetAuthGoogleCallbackUnauthorized with default headers values
func NewGetAuthGoogleCallbackUnauthorized() *GetAuthGoogleCallbackUnauthorized {

	return &GetAuthGoogleCallbackUnauthorized{}
}

// WithPayload adds the payload to the get auth google callback unauthorized response
func (o *GetAuthGoogleCallbackUnauthorized) WithPayload(payload *models.Error) *GetAuthGoogleCallbackUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth google callback unauthorized response
func (o *GetAuthGoogleCallbackUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthGoogleCallbackUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuthGoogleCallbackInternalServerErrorCode is the HTTP code returned for type GetAuthGoogleCallbackInternalServerError
const GetAuthGoogleCallbackInternalServerErrorCode int = 500

/*
GetAuthGoogleCallbackInternalServerError Internal server error

swagger:response getAuthGoogleCallbackInternalServerError
*/
type GetAuthGoogleCallbackInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthGoogleCallbackInternalServerError creates GetAuthGoogleCallbackInternalServerError with default headers values
func NewGetAuthGoogleCallbackInternalServerError() *GetAuthGoogleCallbackInternalServerError {

	return &GetAuthGoogleCallbackInternalServerError{}
}

// WithPayload adds the payload to the get auth google callback internal server error response
func (o *GetAuthGoogleCallbackInternalServerError) WithPayload(payload *models.Error) *GetAuthGoogleCallbackInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth google callback internal server error response
func (o *GetAuthGoogleCallbackInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthGoogleCallbackInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
