// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/auth/internal/models"
)

// GetAuthMeOKCode is the HTTP code returned for type GetAuthMeOK
const GetAuthMeOKCode int = 200

/*
GetAuthMeOK Success

swagger:response getAuthMeOK
*/
type GetAuthMeOK struct {

	/*
	  In: Body
	*/
	Payload *GetAuthMeOKBody `json:"body,omitempty"`
}

// NewGetAuthMeOK creates GetAuthMeOK with default headers values
func NewGetAuthMeOK() *GetAuthMeOK {

	return &GetAuthMeOK{}
}

// WithPayload adds the payload to the get auth me o k response
func (o *GetAuthMeOK) WithPayload(payload *GetAuthMeOKBody) *GetAuthMeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth me o k response
func (o *GetAuthMeOK) SetPayload(payload *GetAuthMeOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthMeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuthMeUnauthorizedCode is the HTTP code returned for type GetAuthMeUnauthorized
const GetAuthMeUnauthorizedCode int = 401

/*
GetAuthMeUnauthorized Unauthorized

swagger:response getAuthMeUnauthorized
*/
type GetAuthMeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthMeUnauthorized creates GetAuthMeUnauthorized with default headers values
func NewGetAuthMeUnauthorized() *GetAuthMeUnauthorized {

	return &GetAuthMeUnauthorized{}
}

// WithPayload adds the payload to the get auth me unauthorized response
func (o *GetAuthMeUnauthorized) WithPayload(payload *models.Error) *GetAuthMeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth me unauthorized response
func (o *GetAuthMeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthMeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
