// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAuthMetricsOKCode is the HTTP code returned for type GetAuthMetricsOK
const GetAuthMetricsOKCode int = 200

/*
GetAuthMetricsOK ok

swagger:response getAuthMetricsOK
*/
type GetAuthMetricsOK struct {
}

// NewGetAuthMetricsOK creates GetAuthMetricsOK with default headers values
func NewGetAuthMetricsOK() *GetAuthMetricsOK {

	return &GetAuthMetricsOK{}
}

// WriteResponse to the client
func (o *GetAuthMetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
