// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAuthGoogleCallbackHandlerFunc turns a function with the right signature into a get auth google callback handler
type GetAuthGoogleCallbackHandlerFunc func(GetAuthGoogleCallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthGoogleCallbackHandlerFunc) Handle(params GetAuthGoogleCallbackParams) middleware.Responder {
	return fn(params)
}

// GetAuthGoogleCallbackHandler interface for that can handle valid get auth google callback params
type GetAuthGoogleCallbackHandler interface {
	Handle(GetAuthGoogleCallbackParams) middleware.Responder
}

// NewGetAuthGoogleCallback creates a new http.Handler for the get auth google callback operation
func NewGetAuthGoogleCallback(ctx *middleware.Context, handler GetAuthGoogleCallbackHandler) *GetAuthGoogleCallback {
	return &GetAuthGoogleCallback{Context: ctx, Handler: handler}
}

/*
	GetAuthGoogleCallback swagger:route GET /auth/google/callback getAuthGoogleCallback

Handle Google OAuth callback
*/
type GetAuthGoogleCallback struct {
	Context *middleware.Context
	Handler GetAuthGoogleCallbackHandler
}

func (o *GetAuthGoogleCallback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthGoogleCallbackParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAuthGoogleCallbackOKBody get auth google callback o k body
//
// swagger:model GetAuthGoogleCallbackOKBody
type GetAuthGoogleCallbackOKBody struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this get auth google callback o k body
func (o *GetAuthGoogleCallbackOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get auth google callback o k body based on context it is used
func (o *GetAuthGoogleCallbackOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAuthGoogleCallbackOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAuthGoogleCallbackOKBody) UnmarshalBinary(b []byte) error {
	var res GetAuthGoogleCallbackOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
