// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/auth/internal/models"
)

// GetAuthGoogleLoginFoundCode is the HTTP code returned for type GetAuthGoogleLoginFound
const GetAuthGoogleLoginFoundCode int = 302

/*
GetAuthGoogleLoginFound Redirect to Google OAuth

swagger:response getAuthGoogleLoginFound
*/
type GetAuthGoogleLoginFound struct {
}

// NewGetAuthGoogleLoginFound creates GetAuthGoogleLoginFound with default headers values
func NewGetAuthGoogleLoginFound() *GetAuthGoogleLoginFound {

	return &GetAuthGoogleLoginFound{}
}

// WriteResponse to the client
func (o *GetAuthGoogleLoginFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// GetAuthGoogleLoginInternalServerErrorCode is the HTTP code returned for type GetAuthGoogleLoginInternalServerError
const GetAuthGoogleLoginInternalServerErrorCode int = 500

/*
GetAuthGoogleLoginInternalServerError Internal server error

swagger:response getAuthGoogleLoginInternalServerError
*/
type GetAuthGoogleLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthGoogleLoginInternalServerError creates GetAuthGoogleLoginInternalServerError with default headers values
func NewGetAuthGoogleLoginInternalServerError() *GetAuthGoogleLoginInternalServerError {

	return &GetAuthGoogleLoginInternalServerError{}
}

// WithPayload adds the payload to the get auth google login internal server error response
func (o *GetAuthGoogleLoginInternalServerError) WithPayload(payload *models.Error) *GetAuthGoogleLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth google login internal server error response
func (o *GetAuthGoogleLoginInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthGoogleLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
