// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetAuthMeParams creates a new GetAuthMeParams object
//
// There are no default values defined in the spec.
func NewGetAuthMeParams() GetAuthMeParams {

	return GetAuthMeParams{}
}

// GetAuthMeParams contains all the bound params for the get auth me operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAuthMe
type GetAuthMeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*JWT token
	  Required: true
	  In: header
	*/
	APIKey string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAuthMeParams() beforehand.
func (o *GetAuthMeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindAPIKey(r.Header[http.CanonicalHeaderKey("api_key")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAPIKey binds and validates parameter APIKey from header.
func (o *GetAuthMeParams) bindAPIKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("api_key", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("api_key", "header", raw); err != nil {
		return err
	}
	o.APIKey = raw

	return nil
}
