// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAuthMeHandlerFunc turns a function with the right signature into a get auth me handler
type GetAuthMeHandlerFunc func(GetAuthMeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthMeHandlerFunc) Handle(params GetAuthMeParams) middleware.Responder {
	return fn(params)
}

// GetAuthMeHandler interface for that can handle valid get auth me params
type GetAuthMeHandler interface {
	Handle(GetAuthMeParams) middleware.Responder
}

// NewGetAuthMe creates a new http.Handler for the get auth me operation
func NewGetAuthMe(ctx *middleware.Context, handler GetAuthMeHandler) *GetAuthMe {
	return &GetAuthMe{Context: ctx, Handler: handler}
}

/*
	GetAuthMe swagger:route GET /auth/me getAuthMe

Get current user info by token
*/
type GetAuthMe struct {
	Context *middleware.Context
	Handler GetAuthMeHandler
}

func (o *GetAuthMe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthMeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAuthMeOKBody get auth me o k body
//
// swagger:model GetAuthMeOKBody
type GetAuthMeOKBody struct {

	// email
	Email string `json:"email,omitempty"`

	// login
	Login string `json:"login,omitempty"`

	// role
	// Enum: ["driver","owner","admin"]
	Role string `json:"role,omitempty"`

	// telegram id
	TelegramID int64 `json:"telegram_id,omitempty"`

	// Keycloak user ID (UUID)
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this get auth me o k body
func (o *GetAuthMeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getAuthMeOKBodyTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["driver","owner","admin"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAuthMeOKBodyTypeRolePropEnum = append(getAuthMeOKBodyTypeRolePropEnum, v)
	}
}

const (

	// GetAuthMeOKBodyRoleDriver captures enum value "driver"
	GetAuthMeOKBodyRoleDriver string = "driver"

	// GetAuthMeOKBodyRoleOwner captures enum value "owner"
	GetAuthMeOKBodyRoleOwner string = "owner"

	// GetAuthMeOKBodyRoleAdmin captures enum value "admin"
	GetAuthMeOKBodyRoleAdmin string = "admin"
)

// prop value enum
func (o *GetAuthMeOKBody) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getAuthMeOKBodyTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetAuthMeOKBody) validateRole(formats strfmt.Registry) error {
	if swag.IsZero(o.Role) { // not required
		return nil
	}

	// value enum
	if err := o.validateRoleEnum("getAuthMeOK"+"."+"role", "body", o.Role); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get auth me o k body based on context it is used
func (o *GetAuthMeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAuthMeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAuthMeOKBody) UnmarshalBinary(b []byte) error {
	var res GetAuthMeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
