// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostAuthRegisterHandlerFunc turns a function with the right signature into a post auth register handler
type PostAuthRegisterHandlerFunc func(PostAuthRegisterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuthRegisterHandlerFunc) Handle(params PostAuthRegisterParams) middleware.Responder {
	return fn(params)
}

// PostAuthRegisterHandler interface for that can handle valid post auth register params
type PostAuthRegisterHandler interface {
	Handle(PostAuthRegisterParams) middleware.Responder
}

// NewPostAuthRegister creates a new http.Handler for the post auth register operation
func NewPostAuthRegister(ctx *middleware.Context, handler PostAuthRegisterHandler) *PostAuthRegister {
	return &PostAuthRegister{Context: ctx, Handler: handler}
}

/*
	PostAuthRegister swagger:route POST /auth/register postAuthRegister

Register user by username and password
*/
type PostAuthRegister struct {
	Context *middleware.Context
	Handler PostAuthRegisterHandler
}

func (o *PostAuthRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuthRegisterParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostAuthRegisterBody post auth register body
//
// swagger:model PostAuthRegisterBody
type PostAuthRegisterBody struct {

	// email
	// Required: true
	Email *string `json:"email"`

	// login
	// Required: true
	Login *string `json:"login"`

	// password
	// Required: true
	Password *string `json:"password"`

	// role
	// Required: true
	// Enum: ["driver","owner"]
	Role *string `json:"role"`

	// telegram id
	// Required: true
	TelegramID *int64 `json:"telegram_id"`
}

// Validate validates this post auth register body
func (o *PostAuthRegisterBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTelegramID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAuthRegisterBody) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

func (o *PostAuthRegisterBody) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"login", "body", o.Login); err != nil {
		return err
	}

	return nil
}

func (o *PostAuthRegisterBody) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"password", "body", o.Password); err != nil {
		return err
	}

	return nil
}

var postAuthRegisterBodyTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["driver","owner"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postAuthRegisterBodyTypeRolePropEnum = append(postAuthRegisterBodyTypeRolePropEnum, v)
	}
}

const (

	// PostAuthRegisterBodyRoleDriver captures enum value "driver"
	PostAuthRegisterBodyRoleDriver string = "driver"

	// PostAuthRegisterBodyRoleOwner captures enum value "owner"
	PostAuthRegisterBodyRoleOwner string = "owner"
)

// prop value enum
func (o *PostAuthRegisterBody) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postAuthRegisterBodyTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostAuthRegisterBody) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"role", "body", o.Role); err != nil {
		return err
	}

	// value enum
	if err := o.validateRoleEnum("body"+"."+"role", "body", *o.Role); err != nil {
		return err
	}

	return nil
}

func (o *PostAuthRegisterBody) validateTelegramID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"telegram_id", "body", o.TelegramID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post auth register body based on context it is used
func (o *PostAuthRegisterBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAuthRegisterBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAuthRegisterBody) UnmarshalBinary(b []byte) error {
	var res PostAuthRegisterBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostAuthRegisterOKBody post auth register o k body
//
// swagger:model PostAuthRegisterOKBody
type PostAuthRegisterOKBody struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this post auth register o k body
func (o *PostAuthRegisterOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post auth register o k body based on context it is used
func (o *PostAuthRegisterOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAuthRegisterOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAuthRegisterOKBody) UnmarshalBinary(b []byte) error {
	var res PostAuthRegisterOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
