// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Parking Net Go project | Parking svc",
    "title": "parkings.parking",
    "version": "0.3.0"
  },
  "paths": {
    "/metrics": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "instruments"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    },
    "/parking": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Get suitable parking places",
        "operationId": "get_parkings",
        "parameters": [
          {
            "type": "string",
            "name": "city",
            "in": "query"
          },
          {
            "type": "string",
            "name": "name",
            "in": "query"
          },
          {
            "enum": [
              "outdoor",
              "covered",
              "underground",
              "multi-level"
            ],
            "type": "string",
            "name": "parking_type",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter parking places by owner ID (for owners to get their own parkings)",
            "name": "owner_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ParkingPlace"
              }
            }
          },
          "404": {
            "description": "Suitable parking places not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Create parking place",
        "operationId": "create_parking",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/parking/{parking_id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Get parking place info by id",
        "operationId": "get_parking_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of parking place to return",
            "name": "parking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          },
          "404": {
            "description": "Parking place not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Update parking place",
        "operationId": "update_parking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of parking place to change",
            "name": "parking_id",
            "in": "path",
            "required": true
          },
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "No such element",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Delete parking place",
        "operationId": "delete_parking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of parking place to delete",
            "name": "parking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Result"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Parking place not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "ParkingPlace": {
      "type": "object",
      "required": [
        "name",
        "city",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "example": "Red Square №1"
        },
        "capacity": {
          "description": "total number of parking spots",
          "type": "integer",
          "format": "int64"
        },
        "city": {
          "type": "string",
          "example": "Moscow"
        },
        "hourly_rate": {
          "description": "hourly parking rate",
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string",
          "example": "Central Parking"
        },
        "owner_id": {
          "type": "string"
        },
        "parking_type": {
          "description": "type of parking facility",
          "type": "string",
          "enum": [
            "outdoor",
            "covered",
            "underground",
            "multi-level"
          ]
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Parking operations",
      "name": "parking"
    },
    {
      "description": "Inner operations",
      "name": "instruments"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Parking Net Go project | Parking svc",
    "title": "parkings.parking",
    "version": "0.3.0"
  },
  "paths": {
    "/metrics": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "instruments"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    },
    "/parking": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Get suitable parking places",
        "operationId": "get_parkings",
        "parameters": [
          {
            "type": "string",
            "name": "city",
            "in": "query"
          },
          {
            "type": "string",
            "name": "name",
            "in": "query"
          },
          {
            "enum": [
              "outdoor",
              "covered",
              "underground",
              "multi-level"
            ],
            "type": "string",
            "name": "parking_type",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter parking places by owner ID (for owners to get their own parkings)",
            "name": "owner_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ParkingPlace"
              }
            }
          },
          "404": {
            "description": "Suitable parking places not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Create parking place",
        "operationId": "create_parking",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/parking/{parking_id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Get parking place info by id",
        "operationId": "get_parking_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of parking place to return",
            "name": "parking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          },
          "404": {
            "description": "Parking place not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Update parking place",
        "operationId": "update_parking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of parking place to change",
            "name": "parking_id",
            "in": "path",
            "required": true
          },
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ParkingPlace"
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "No such element",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "parking"
        ],
        "summary": "Delete parking place",
        "operationId": "delete_parking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of parking place to delete",
            "name": "parking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Result"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Parking place not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "ParkingPlace": {
      "type": "object",
      "required": [
        "name",
        "city",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "example": "Red Square №1"
        },
        "capacity": {
          "description": "total number of parking spots",
          "type": "integer",
          "format": "int64"
        },
        "city": {
          "type": "string",
          "example": "Moscow"
        },
        "hourly_rate": {
          "description": "hourly parking rate",
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string",
          "example": "Central Parking"
        },
        "owner_id": {
          "type": "string"
        },
        "parking_type": {
          "description": "type of parking facility",
          "type": "string",
          "enum": [
            "outdoor",
            "covered",
            "underground",
            "multi-level"
          ]
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Parking operations",
      "name": "parking"
    },
    {
      "description": "Inner operations",
      "name": "instruments"
    }
  ]
}`))
}
