// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/booking/internal/models"
)

// CreateBookingOKCode is the HTTP code returned for type CreateBookingOK
const CreateBookingOKCode int = 200

/*
CreateBookingOK successful operation

swagger:response createBookingOK
*/
type CreateBookingOK struct {

	/*
	  In: Body
	*/
	Payload *CreateBookingOKBody `json:"body,omitempty"`
}

// NewCreateBookingOK creates CreateBookingOK with default headers values
func NewCreateBookingOK() *CreateBookingOK {

	return &CreateBookingOK{}
}

// WithPayload adds the payload to the create booking o k response
func (o *CreateBookingOK) WithPayload(payload *CreateBookingOKBody) *CreateBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create booking o k response
func (o *CreateBookingOK) SetPayload(payload *CreateBookingOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBookingBadRequestCode is the HTTP code returned for type CreateBookingBadRequest
const CreateBookingBadRequestCode int = 400

/*
CreateBookingBadRequest Incorrect data

swagger:response createBookingBadRequest
*/
type CreateBookingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBookingBadRequest creates CreateBookingBadRequest with default headers values
func NewCreateBookingBadRequest() *CreateBookingBadRequest {

	return &CreateBookingBadRequest{}
}

// WithPayload adds the payload to the create booking bad request response
func (o *CreateBookingBadRequest) WithPayload(payload *models.Error) *CreateBookingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create booking bad request response
func (o *CreateBookingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBookingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBookingForbiddenCode is the HTTP code returned for type CreateBookingForbidden
const CreateBookingForbiddenCode int = 403

/*
CreateBookingForbidden No access

swagger:response createBookingForbidden
*/
type CreateBookingForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBookingForbidden creates CreateBookingForbidden with default headers values
func NewCreateBookingForbidden() *CreateBookingForbidden {

	return &CreateBookingForbidden{}
}

// WithPayload adds the payload to the create booking forbidden response
func (o *CreateBookingForbidden) WithPayload(payload *models.Error) *CreateBookingForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create booking forbidden response
func (o *CreateBookingForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBookingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
