// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/booking/internal/models"
)

// DeleteBookingHandlerFunc turns a function with the right signature into a delete booking handler
type DeleteBookingHandlerFunc func(DeleteBookingParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBookingHandlerFunc) Handle(params DeleteBookingParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteBookingHandler interface for that can handle valid delete booking params
type DeleteBookingHandler interface {
	Handle(DeleteBookingParams, *models.User) middleware.Responder
}

// NewDeleteBooking creates a new http.Handler for the delete booking operation
func NewDeleteBooking(ctx *middleware.Context, handler DeleteBookingHandler) *DeleteBooking {
	return &DeleteBooking{Context: ctx, Handler: handler}
}

/*
	DeleteBooking swagger:route DELETE /booking/{booking_id} driver owner deleteBooking

Delete booking
*/
type DeleteBooking struct {
	Context *middleware.Context
	Handler DeleteBookingHandler
}

func (o *DeleteBooking) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteBookingParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
