// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/booking/internal/models"
)

// DeleteBookingOKCode is the HTTP code returned for type DeleteBookingOK
const DeleteBookingOKCode int = 200

/*
DeleteBookingOK successful operation

swagger:response deleteBookingOK
*/
type DeleteBookingOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteBookingOK creates DeleteBookingOK with default headers values
func NewDeleteBookingOK() *DeleteBookingOK {

	return &DeleteBookingOK{}
}

// WithPayload adds the payload to the delete booking o k response
func (o *DeleteBookingOK) WithPayload(payload *models.Result) *DeleteBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete booking o k response
func (o *DeleteBookingOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBookingForbiddenCode is the HTTP code returned for type DeleteBookingForbidden
const DeleteBookingForbiddenCode int = 403

/*
DeleteBookingForbidden No access

swagger:response deleteBookingForbidden
*/
type DeleteBookingForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBookingForbidden creates DeleteBookingForbidden with default headers values
func NewDeleteBookingForbidden() *DeleteBookingForbidden {

	return &DeleteBookingForbidden{}
}

// WithPayload adds the payload to the delete booking forbidden response
func (o *DeleteBookingForbidden) WithPayload(payload *models.Error) *DeleteBookingForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete booking forbidden response
func (o *DeleteBookingForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBookingNotFoundCode is the HTTP code returned for type DeleteBookingNotFound
const DeleteBookingNotFoundCode int = 404

/*
DeleteBookingNotFound Booking not found

swagger:response deleteBookingNotFound
*/
type DeleteBookingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBookingNotFound creates DeleteBookingNotFound with default headers values
func NewDeleteBookingNotFound() *DeleteBookingNotFound {

	return &DeleteBookingNotFound{}
}

// WithPayload adds the payload to the delete booking not found response
func (o *DeleteBookingNotFound) WithPayload(payload *models.Error) *DeleteBookingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete booking not found response
func (o *DeleteBookingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
