// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/booking/internal/models"
)

// GetBookingByIDHandlerFunc turns a function with the right signature into a get booking by id handler
type GetBookingByIDHandlerFunc func(GetBookingByIDParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBookingByIDHandlerFunc) Handle(params GetBookingByIDParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetBookingByIDHandler interface for that can handle valid get booking by id params
type GetBookingByIDHandler interface {
	Handle(GetBookingByIDParams, *models.User) middleware.Responder
}

// NewGetBookingByID creates a new http.Handler for the get booking by id operation
func NewGetBookingByID(ctx *middleware.Context, handler GetBookingByIDHandler) *GetBookingByID {
	return &GetBookingByID{Context: ctx, Handler: handler}
}

/*
	GetBookingByID swagger:route GET /booking/{booking_id} driver owner getBookingById

Get booking info by id
*/
type GetBookingByID struct {
	Context *middleware.Context
	Handler GetBookingByIDHandler
}

func (o *GetBookingByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBookingByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
