// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/booking/internal/models"
)

// UpdateBookingOKCode is the HTTP code returned for type UpdateBookingOK
const UpdateBookingOKCode int = 200

/*
UpdateBookingOK successful operation

swagger:response updateBookingOK
*/
type UpdateBookingOK struct {

	/*
	  In: Body
	*/
	Payload *models.Booking `json:"body,omitempty"`
}

// NewUpdateBookingOK creates UpdateBookingOK with default headers values
func NewUpdateBookingOK() *UpdateBookingOK {

	return &UpdateBookingOK{}
}

// WithPayload adds the payload to the update booking o k response
func (o *UpdateBookingOK) WithPayload(payload *models.Booking) *UpdateBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update booking o k response
func (o *UpdateBookingOK) SetPayload(payload *models.Booking) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateBookingBadRequestCode is the HTTP code returned for type UpdateBookingBadRequest
const UpdateBookingBadRequestCode int = 400

/*
UpdateBookingBadRequest Incorrect data

swagger:response updateBookingBadRequest
*/
type UpdateBookingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateBookingBadRequest creates UpdateBookingBadRequest with default headers values
func NewUpdateBookingBadRequest() *UpdateBookingBadRequest {

	return &UpdateBookingBadRequest{}
}

// WithPayload adds the payload to the update booking bad request response
func (o *UpdateBookingBadRequest) WithPayload(payload *models.Error) *UpdateBookingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update booking bad request response
func (o *UpdateBookingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBookingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateBookingForbiddenCode is the HTTP code returned for type UpdateBookingForbidden
const UpdateBookingForbiddenCode int = 403

/*
UpdateBookingForbidden No access

swagger:response updateBookingForbidden
*/
type UpdateBookingForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateBookingForbidden creates UpdateBookingForbidden with default headers values
func NewUpdateBookingForbidden() *UpdateBookingForbidden {

	return &UpdateBookingForbidden{}
}

// WithPayload adds the payload to the update booking forbidden response
func (o *UpdateBookingForbidden) WithPayload(payload *models.Error) *UpdateBookingForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update booking forbidden response
func (o *UpdateBookingForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateBookingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
