// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Parking Net Go project | Booking svc",
    "title": "parkings.booking",
    "version": "0.3.0"
  },
  "paths": {
    "/booking": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get suitable bookings",
        "operationId": "get_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "parking_place_id",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter bookings by user ID (for drivers to get their own bookings)",
            "name": "user_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Booking"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver"
        ],
        "summary": "Create booking",
        "operationId": "create_booking",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "required": [
                "parking_place_id",
                "date_from",
                "date_to"
              ],
              "properties": {
                "date_from": {
                  "type": "string"
                },
                "date_to": {
                  "type": "string"
                },
                "parking_place_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "booking_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/booking/{booking_id}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get booking info by id",
        "operationId": "get_booking_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to return",
            "name": "booking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Update booking",
        "operationId": "update_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to change",
            "name": "booking_id",
            "in": "path",
            "required": true
          },
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Delete booking",
        "operationId": "delete_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to delete",
            "name": "booking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Result"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "instruments"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    }
  },
  "definitions": {
    "Booking": {
      "type": "object",
      "required": [
        "date_from",
        "date_to",
        "parking_place_id"
      ],
      "properties": {
        "booking_id": {
          "type": "integer",
          "format": "int64"
        },
        "date_from": {
          "type": "string",
          "pattern": "^\\d{2}-\\d{2}-\\d{4}$",
          "example": "31-12-2024"
        },
        "date_to": {
          "type": "string",
          "pattern": "^\\d{2}-\\d{2}-\\d{4}$",
          "example": "31-12-2025"
        },
        "full_cost": {
          "type": "integer",
          "format": "int64"
        },
        "parking_place_id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "description": "status of booking",
          "type": "string",
          "enum": [
            "Waiting",
            "Confirmed",
            "Canceled"
          ]
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "ParkingPlace": {
      "type": "object",
      "required": [
        "name",
        "city",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "example": "Red Square №1"
        },
        "capacity": {
          "description": "total number of parking spots",
          "type": "integer",
          "format": "int64"
        },
        "city": {
          "type": "string",
          "example": "Moscow"
        },
        "hourly_rate": {
          "description": "hourly parking rate",
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string",
          "example": "Central Parking"
        },
        "owner_id": {
          "type": "string"
        },
        "parking_type": {
          "description": "type of parking facility",
          "type": "string",
          "enum": [
            "outdoor",
            "covered",
            "underground",
            "multi-level"
          ]
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Driver operations",
      "name": "driver"
    },
    {
      "description": "Parking owner operations",
      "name": "owner"
    },
    {
      "description": "Inner operations",
      "name": "instruments"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Parking Net Go project | Booking svc",
    "title": "parkings.booking",
    "version": "0.3.0"
  },
  "paths": {
    "/booking": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get suitable bookings",
        "operationId": "get_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "parking_place_id",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Filter bookings by user ID (for drivers to get their own bookings)",
            "name": "user_id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Booking"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver"
        ],
        "summary": "Create booking",
        "operationId": "create_booking",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "required": [
                "parking_place_id",
                "date_from",
                "date_to"
              ],
              "properties": {
                "date_from": {
                  "type": "string"
                },
                "date_to": {
                  "type": "string"
                },
                "parking_place_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "booking_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/booking/{booking_id}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get booking info by id",
        "operationId": "get_booking_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to return",
            "name": "booking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Update booking",
        "operationId": "update_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to change",
            "name": "booking_id",
            "in": "path",
            "required": true
          },
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Delete booking",
        "operationId": "delete_booking",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of booking to delete",
            "name": "booking_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Result"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Booking not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "instruments"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    }
  },
  "definitions": {
    "Booking": {
      "type": "object",
      "required": [
        "date_from",
        "date_to",
        "parking_place_id"
      ],
      "properties": {
        "booking_id": {
          "type": "integer",
          "format": "int64"
        },
        "date_from": {
          "type": "string",
          "pattern": "^\\d{2}-\\d{2}-\\d{4}$",
          "example": "31-12-2024"
        },
        "date_to": {
          "type": "string",
          "pattern": "^\\d{2}-\\d{2}-\\d{4}$",
          "example": "31-12-2025"
        },
        "full_cost": {
          "type": "integer",
          "format": "int64"
        },
        "parking_place_id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "description": "status of booking",
          "type": "string",
          "enum": [
            "Waiting",
            "Confirmed",
            "Canceled"
          ]
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "ParkingPlace": {
      "type": "object",
      "required": [
        "name",
        "city",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "example": "Red Square №1"
        },
        "capacity": {
          "description": "total number of parking spots",
          "type": "integer",
          "format": "int64"
        },
        "city": {
          "type": "string",
          "example": "Moscow"
        },
        "hourly_rate": {
          "description": "hourly parking rate",
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string",
          "example": "Central Parking"
        },
        "owner_id": {
          "type": "string"
        },
        "parking_type": {
          "description": "type of parking facility",
          "type": "string",
          "enum": [
            "outdoor",
            "covered",
            "underground",
            "multi-level"
          ]
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Driver operations",
      "name": "driver"
    },
    {
      "description": "Parking owner operations",
      "name": "owner"
    },
    {
      "description": "Inner operations",
      "name": "instruments"
    }
  ]
}`))
}
