// Code generated by go-swagger; DO NOT EDIT.

// Package restapi parkings.payment
//
//	Parking Net Go project | Payment svc
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
