// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Parking Net Go project | Payment svc",
    "title": "parkings.payment",
    "version": "0.1.0"
  },
  "paths": {
    "/metrics": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "instruments"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    },
    "/payment/balance": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get user balance",
        "operationId": "get_balance",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Balance"
            }
          },
          "404": {
            "description": "Balance not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/activate": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Activate promocode to add balance",
        "operationId": "activate_promocode",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ActivatePromocodeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Balance"
            }
          },
          "400": {
            "description": "Invalid or expired promocode",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Promocode not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/create": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "admin"
        ],
        "summary": "Create promocode with custom parameters",
        "operationId": "create_promocode",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreatePromocodeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/PromocodeResponse"
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Admin access required",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/generate": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Generate promocode from user balance",
        "operationId": "generate_promocode",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GeneratePromocodeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/PromocodeResponse"
            }
          },
          "400": {
            "description": "Insufficient funds or invalid request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/{code}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner",
          "admin"
        ],
        "summary": "Get promocode information",
        "operationId": "get_promocode",
        "parameters": [
          {
            "type": "string",
            "description": "Promocode to check",
            "name": "code",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/PromocodeInfo"
            }
          },
          "404": {
            "description": "Promocode not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/transactions": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get user transactions",
        "operationId": "get_transactions",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "default": 50,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Transaction"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActivatePromocodeRequest": {
      "type": "object",
      "required": [
        "code"
      ],
      "properties": {
        "code": {
          "description": "Promocode to activate",
          "type": "string"
        }
      }
    },
    "Balance": {
      "type": "object",
      "required": [
        "balance",
        "currency",
        "user_id"
      ],
      "properties": {
        "balance": {
          "description": "Current balance in cents",
          "type": "integer",
          "format": "int64"
        },
        "currency": {
          "type": "string",
          "default": "USD"
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "CreatePromocodeRequest": {
      "type": "object",
      "required": [
        "amount",
        "max_uses"
      ],
      "properties": {
        "amount": {
          "description": "Promocode value in cents",
          "type": "integer",
          "format": "int64"
        },
        "code": {
          "description": "Custom promocode (optional, will be generated if not provided)",
          "type": "string"
        },
        "expires_at": {
          "description": "Expiration date (optional)",
          "type": "string",
          "format": "date-time"
        },
        "max_uses": {
          "description": "Maximum number of times this promocode can be used",
          "type": "integer",
          "format": "int64",
          "default": 1
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "GeneratePromocodeRequest": {
      "type": "object",
      "required": [
        "amount"
      ],
      "properties": {
        "amount": {
          "description": "Amount in cents to generate promocode for",
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "PromocodeInfo": {
      "type": "object",
      "properties": {
        "amount": {
          "description": "Promocode value in cents",
          "type": "integer",
          "format": "int64"
        },
        "code": {
          "type": "string"
        },
        "expires_at": {
          "type": "string",
          "format": "date-time"
        },
        "is_active": {
          "description": "Whether promocode is still valid and can be used",
          "type": "boolean"
        },
        "max_uses": {
          "type": "integer",
          "format": "int64"
        },
        "remaining_uses": {
          "type": "integer",
          "format": "int64"
        },
        "used_count": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "PromocodeResponse": {
      "type": "object",
      "properties": {
        "amount": {
          "description": "Promocode value in cents",
          "type": "integer",
          "format": "int64"
        },
        "code": {
          "description": "Generated promocode",
          "type": "string"
        },
        "expires_at": {
          "description": "Expiration date",
          "type": "string",
          "format": "date-time"
        },
        "max_uses": {
          "description": "Maximum number of uses",
          "type": "integer",
          "format": "int64"
        },
        "remaining_uses": {
          "description": "Remaining uses",
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Transaction": {
      "type": "object",
      "properties": {
        "amount": {
          "description": "Transaction amount in cents (negative for charges, positive for payments)",
          "type": "integer",
          "format": "int64"
        },
        "booking_id": {
          "type": "integer",
          "format": "int64"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "completed",
            "failed",
            "canceled"
          ]
        },
        "transaction_type": {
          "type": "string",
          "enum": [
            "charge",
            "payment",
            "refund",
            "promocode_activate",
            "promocode_generate"
          ]
        },
        "user_id": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Driver operations",
      "name": "driver"
    },
    {
      "description": "Parking owner operations",
      "name": "owner"
    },
    {
      "description": "Admin operations",
      "name": "admin"
    },
    {
      "description": "Inner operations",
      "name": "instruments"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Parking Net Go project | Payment svc",
    "title": "parkings.payment",
    "version": "0.1.0"
  },
  "paths": {
    "/metrics": {
      "get": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "tags": [
          "instruments"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    },
    "/payment/balance": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get user balance",
        "operationId": "get_balance",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Balance"
            }
          },
          "404": {
            "description": "Balance not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/activate": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Activate promocode to add balance",
        "operationId": "activate_promocode",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ActivatePromocodeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Balance"
            }
          },
          "400": {
            "description": "Invalid or expired promocode",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Promocode not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/create": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "admin"
        ],
        "summary": "Create promocode with custom parameters",
        "operationId": "create_promocode",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreatePromocodeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/PromocodeResponse"
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Admin access required",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/generate": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Generate promocode from user balance",
        "operationId": "generate_promocode",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GeneratePromocodeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/PromocodeResponse"
            }
          },
          "400": {
            "description": "Insufficient funds or invalid request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/promocode/{code}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner",
          "admin"
        ],
        "summary": "Get promocode information",
        "operationId": "get_promocode",
        "parameters": [
          {
            "type": "string",
            "description": "Promocode to check",
            "name": "code",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/PromocodeInfo"
            }
          },
          "404": {
            "description": "Promocode not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/payment/transactions": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "driver",
          "owner"
        ],
        "summary": "Get user transactions",
        "operationId": "get_transactions",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "default": 50,
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "offset",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Transaction"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActivatePromocodeRequest": {
      "type": "object",
      "required": [
        "code"
      ],
      "properties": {
        "code": {
          "description": "Promocode to activate",
          "type": "string"
        }
      }
    },
    "Balance": {
      "type": "object",
      "required": [
        "balance",
        "currency",
        "user_id"
      ],
      "properties": {
        "balance": {
          "description": "Current balance in cents",
          "type": "integer",
          "format": "int64"
        },
        "currency": {
          "type": "string",
          "default": "USD"
        },
        "user_id": {
          "type": "string"
        }
      }
    },
    "CreatePromocodeRequest": {
      "type": "object",
      "required": [
        "amount",
        "max_uses"
      ],
      "properties": {
        "amount": {
          "description": "Promocode value in cents",
          "type": "integer",
          "format": "int64"
        },
        "code": {
          "description": "Custom promocode (optional, will be generated if not provided)",
          "type": "string"
        },
        "expires_at": {
          "description": "Expiration date (optional)",
          "type": "string",
          "format": "date-time"
        },
        "max_uses": {
          "description": "Maximum number of times this promocode can be used",
          "type": "integer",
          "format": "int64",
          "default": 1
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string"
        },
        "error_status_code": {
          "type": "integer"
        }
      }
    },
    "GeneratePromocodeRequest": {
      "type": "object",
      "required": [
        "amount"
      ],
      "properties": {
        "amount": {
          "description": "Amount in cents to generate promocode for",
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "PromocodeInfo": {
      "type": "object",
      "properties": {
        "amount": {
          "description": "Promocode value in cents",
          "type": "integer",
          "format": "int64"
        },
        "code": {
          "type": "string"
        },
        "expires_at": {
          "type": "string",
          "format": "date-time"
        },
        "is_active": {
          "description": "Whether promocode is still valid and can be used",
          "type": "boolean"
        },
        "max_uses": {
          "type": "integer",
          "format": "int64"
        },
        "remaining_uses": {
          "type": "integer",
          "format": "int64"
        },
        "used_count": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "PromocodeResponse": {
      "type": "object",
      "properties": {
        "amount": {
          "description": "Promocode value in cents",
          "type": "integer",
          "format": "int64"
        },
        "code": {
          "description": "Generated promocode",
          "type": "string"
        },
        "expires_at": {
          "description": "Expiration date",
          "type": "string",
          "format": "date-time"
        },
        "max_uses": {
          "description": "Maximum number of uses",
          "type": "integer",
          "format": "int64"
        },
        "remaining_uses": {
          "description": "Remaining uses",
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Transaction": {
      "type": "object",
      "properties": {
        "amount": {
          "description": "Transaction amount in cents (negative for charges, positive for payments)",
          "type": "integer",
          "format": "int64"
        },
        "booking_id": {
          "type": "integer",
          "format": "int64"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "completed",
            "failed",
            "canceled"
          ]
        },
        "transaction_type": {
          "type": "string",
          "enum": [
            "charge",
            "payment",
            "refund",
            "promocode_activate",
            "promocode_generate"
          ]
        },
        "user_id": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Driver operations",
      "name": "driver"
    },
    {
      "description": "Parking owner operations",
      "name": "owner"
    },
    {
      "description": "Admin operations",
      "name": "admin"
    },
    {
      "description": "Inner operations",
      "name": "instruments"
    }
  ]
}`))
}
