// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// CreateParkingOKCode is the HTTP code returned for type CreateParkingOK
const CreateParkingOKCode int = 200

/*
CreateParkingOK successful operation

swagger:response createParkingOK
*/
type CreateParkingOK struct {

	/*
	  In: Body
	*/
	Payload *CreateParkingOKBody `json:"body,omitempty"`
}

// NewCreateParkingOK creates CreateParkingOK with default headers values
func NewCreateParkingOK() *CreateParkingOK {

	return &CreateParkingOK{}
}

// WithPayload adds the payload to the create parking o k response
func (o *CreateParkingOK) WithPayload(payload *CreateParkingOKBody) *CreateParkingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create parking o k response
func (o *CreateParkingOK) SetPayload(payload *CreateParkingOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateParkingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateParkingBadRequestCode is the HTTP code returned for type CreateParkingBadRequest
const CreateParkingBadRequestCode int = 400

/*
CreateParkingBadRequest Incorrect data

swagger:response createParkingBadRequest
*/
type CreateParkingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateParkingBadRequest creates CreateParkingBadRequest with default headers values
func NewCreateParkingBadRequest() *CreateParkingBadRequest {

	return &CreateParkingBadRequest{}
}

// WithPayload adds the payload to the create parking bad request response
func (o *CreateParkingBadRequest) WithPayload(payload *models.Error) *CreateParkingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create parking bad request response
func (o *CreateParkingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateParkingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateParkingForbiddenCode is the HTTP code returned for type CreateParkingForbidden
const CreateParkingForbiddenCode int = 403

/*
CreateParkingForbidden No access

swagger:response createParkingForbidden
*/
type CreateParkingForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateParkingForbidden creates CreateParkingForbidden with default headers values
func NewCreateParkingForbidden() *CreateParkingForbidden {

	return &CreateParkingForbidden{}
}

// WithPayload adds the payload to the create parking forbidden response
func (o *CreateParkingForbidden) WithPayload(payload *models.Error) *CreateParkingForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create parking forbidden response
func (o *CreateParkingForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateParkingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
