// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// CreateParkingHandlerFunc turns a function with the right signature into a create parking handler
type CreateParkingHandlerFunc func(CreateParkingParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateParkingHandlerFunc) Handle(params CreateParkingParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreateParkingHandler interface for that can handle valid create parking params
type CreateParkingHandler interface {
	Handle(CreateParkingParams, *models.User) middleware.Responder
}

// NewCreateParking creates a new http.Handler for the create parking operation
func NewCreateParking(ctx *middleware.Context, handler CreateParkingHandler) *CreateParking {
	return &CreateParking{Context: ctx, Handler: handler}
}

/*
	CreateParking swagger:route POST /parking parking createParking

Create parking place
*/
type CreateParking struct {
	Context *middleware.Context
	Handler CreateParkingHandler
}

func (o *CreateParking) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateParkingParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateParkingOKBody create parking o k body
//
// swagger:model CreateParkingOKBody
type CreateParkingOKBody struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this create parking o k body
func (o *CreateParkingOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create parking o k body based on context it is used
func (o *CreateParkingOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateParkingOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateParkingOKBody) UnmarshalBinary(b []byte) error {
	var res CreateParkingOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
