// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// CreateParkingServiceOKCode is the HTTP code returned for type CreateParkingServiceOK
const CreateParkingServiceOKCode int = 200

/*
CreateParkingServiceOK successful operation

swagger:response createParkingServiceOK
*/
type CreateParkingServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Service `json:"body,omitempty"`
}

// NewCreateParkingServiceOK creates CreateParkingServiceOK with default headers values
func NewCreateParkingServiceOK() *CreateParkingServiceOK {

	return &CreateParkingServiceOK{}
}

// WithPayload adds the payload to the create parking service o k response
func (o *CreateParkingServiceOK) WithPayload(payload *models.Service) *CreateParkingServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create parking service o k response
func (o *CreateParkingServiceOK) SetPayload(payload *models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateParkingServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateParkingServiceBadRequestCode is the HTTP code returned for type CreateParkingServiceBadRequest
const CreateParkingServiceBadRequestCode int = 400

/*
CreateParkingServiceBadRequest Incorrect data

swagger:response createParkingServiceBadRequest
*/
type CreateParkingServiceBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateParkingServiceBadRequest creates CreateParkingServiceBadRequest with default headers values
func NewCreateParkingServiceBadRequest() *CreateParkingServiceBadRequest {

	return &CreateParkingServiceBadRequest{}
}

// WithPayload adds the payload to the create parking service bad request response
func (o *CreateParkingServiceBadRequest) WithPayload(payload *models.Error) *CreateParkingServiceBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create parking service bad request response
func (o *CreateParkingServiceBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateParkingServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateParkingServiceForbiddenCode is the HTTP code returned for type CreateParkingServiceForbidden
const CreateParkingServiceForbiddenCode int = 403

/*
CreateParkingServiceForbidden No access

swagger:response createParkingServiceForbidden
*/
type CreateParkingServiceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateParkingServiceForbidden creates CreateParkingServiceForbidden with default headers values
func NewCreateParkingServiceForbidden() *CreateParkingServiceForbidden {

	return &CreateParkingServiceForbidden{}
}

// WithPayload adds the payload to the create parking service forbidden response
func (o *CreateParkingServiceForbidden) WithPayload(payload *models.Error) *CreateParkingServiceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create parking service forbidden response
func (o *CreateParkingServiceForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateParkingServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateParkingServiceNotFoundCode is the HTTP code returned for type CreateParkingServiceNotFound
const CreateParkingServiceNotFoundCode int = 404

/*
CreateParkingServiceNotFound Parking place not found

swagger:response createParkingServiceNotFound
*/
type CreateParkingServiceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateParkingServiceNotFound creates CreateParkingServiceNotFound with default headers values
func NewCreateParkingServiceNotFound() *CreateParkingServiceNotFound {

	return &CreateParkingServiceNotFound{}
}

// WithPayload adds the payload to the create parking service not found response
func (o *CreateParkingServiceNotFound) WithPayload(payload *models.Error) *CreateParkingServiceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create parking service not found response
func (o *CreateParkingServiceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateParkingServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
