// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// CreateParkingServiceHandlerFunc turns a function with the right signature into a create parking service handler
type CreateParkingServiceHandlerFunc func(CreateParkingServiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateParkingServiceHandlerFunc) Handle(params CreateParkingServiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreateParkingServiceHandler interface for that can handle valid create parking service params
type CreateParkingServiceHandler interface {
	Handle(CreateParkingServiceParams, *models.User) middleware.Responder
}

// NewCreateParkingService creates a new http.Handler for the create parking service operation
func NewCreateParkingService(ctx *middleware.Context, handler CreateParkingServiceHandler) *CreateParkingService {
	return &CreateParkingService{Context: ctx, Handler: handler}
}

/*
	CreateParkingService swagger:route POST /parking/{parking_id}/services parking createParkingService

Create a service for a parking place
*/
type CreateParkingService struct {
	Context *middleware.Context
	Handler CreateParkingServiceHandler
}

func (o *CreateParkingService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateParkingServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
