// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// DeleteParkingOKCode is the HTTP code returned for type DeleteParkingOK
const DeleteParkingOKCode int = 200

/*
DeleteParkingOK successful operation

swagger:response deleteParkingOK
*/
type DeleteParkingOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteParkingOK creates DeleteParkingOK with default headers values
func NewDeleteParkingOK() *DeleteParkingOK {

	return &DeleteParkingOK{}
}

// WithPayload adds the payload to the delete parking o k response
func (o *DeleteParkingOK) WithPayload(payload *models.Result) *DeleteParkingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete parking o k response
func (o *DeleteParkingOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteParkingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteParkingForbiddenCode is the HTTP code returned for type DeleteParkingForbidden
const DeleteParkingForbiddenCode int = 403

/*
DeleteParkingForbidden No access

swagger:response deleteParkingForbidden
*/
type DeleteParkingForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteParkingForbidden creates DeleteParkingForbidden with default headers values
func NewDeleteParkingForbidden() *DeleteParkingForbidden {

	return &DeleteParkingForbidden{}
}

// WithPayload adds the payload to the delete parking forbidden response
func (o *DeleteParkingForbidden) WithPayload(payload *models.Error) *DeleteParkingForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete parking forbidden response
func (o *DeleteParkingForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteParkingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteParkingNotFoundCode is the HTTP code returned for type DeleteParkingNotFound
const DeleteParkingNotFoundCode int = 404

/*
DeleteParkingNotFound Parking place not found

swagger:response deleteParkingNotFound
*/
type DeleteParkingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteParkingNotFound creates DeleteParkingNotFound with default headers values
func NewDeleteParkingNotFound() *DeleteParkingNotFound {

	return &DeleteParkingNotFound{}
}

// WithPayload adds the payload to the delete parking not found response
func (o *DeleteParkingNotFound) WithPayload(payload *models.Error) *DeleteParkingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete parking not found response
func (o *DeleteParkingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteParkingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
