// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// DeleteParkingHandlerFunc turns a function with the right signature into a delete parking handler
type DeleteParkingHandlerFunc func(DeleteParkingParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteParkingHandlerFunc) Handle(params DeleteParkingParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteParkingHandler interface for that can handle valid delete parking params
type DeleteParkingHandler interface {
	Handle(DeleteParkingParams, *models.User) middleware.Responder
}

// NewDeleteParking creates a new http.Handler for the delete parking operation
func NewDeleteParking(ctx *middleware.Context, handler DeleteParkingHandler) *DeleteParking {
	return &DeleteParking{Context: ctx, Handler: handler}
}

/*
	DeleteParking swagger:route DELETE /parking/{parking_id} parking deleteParking

Delete parking place
*/
type DeleteParking struct {
	Context *middleware.Context
	Handler DeleteParkingHandler
}

func (o *DeleteParking) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteParkingParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
