// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// DeleteParkingServiceOKCode is the HTTP code returned for type DeleteParkingServiceOK
const DeleteParkingServiceOKCode int = 200

/*
DeleteParkingServiceOK successful operation

swagger:response deleteParkingServiceOK
*/
type DeleteParkingServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Result `json:"body,omitempty"`
}

// NewDeleteParkingServiceOK creates DeleteParkingServiceOK with default headers values
func NewDeleteParkingServiceOK() *DeleteParkingServiceOK {

	return &DeleteParkingServiceOK{}
}

// WithPayload adds the payload to the delete parking service o k response
func (o *DeleteParkingServiceOK) WithPayload(payload *models.Result) *DeleteParkingServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete parking service o k response
func (o *DeleteParkingServiceOK) SetPayload(payload *models.Result) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteParkingServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteParkingServiceForbiddenCode is the HTTP code returned for type DeleteParkingServiceForbidden
const DeleteParkingServiceForbiddenCode int = 403

/*
DeleteParkingServiceForbidden No access

swagger:response deleteParkingServiceForbidden
*/
type DeleteParkingServiceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteParkingServiceForbidden creates DeleteParkingServiceForbidden with default headers values
func NewDeleteParkingServiceForbidden() *DeleteParkingServiceForbidden {

	return &DeleteParkingServiceForbidden{}
}

// WithPayload adds the payload to the delete parking service forbidden response
func (o *DeleteParkingServiceForbidden) WithPayload(payload *models.Error) *DeleteParkingServiceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete parking service forbidden response
func (o *DeleteParkingServiceForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteParkingServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteParkingServiceNotFoundCode is the HTTP code returned for type DeleteParkingServiceNotFound
const DeleteParkingServiceNotFoundCode int = 404

/*
DeleteParkingServiceNotFound Service not found

swagger:response deleteParkingServiceNotFound
*/
type DeleteParkingServiceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteParkingServiceNotFound creates DeleteParkingServiceNotFound with default headers values
func NewDeleteParkingServiceNotFound() *DeleteParkingServiceNotFound {

	return &DeleteParkingServiceNotFound{}
}

// WithPayload adds the payload to the delete parking service not found response
func (o *DeleteParkingServiceNotFound) WithPayload(payload *models.Error) *DeleteParkingServiceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete parking service not found response
func (o *DeleteParkingServiceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteParkingServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
