// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// DeleteParkingServiceHandlerFunc turns a function with the right signature into a delete parking service handler
type DeleteParkingServiceHandlerFunc func(DeleteParkingServiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteParkingServiceHandlerFunc) Handle(params DeleteParkingServiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteParkingServiceHandler interface for that can handle valid delete parking service params
type DeleteParkingServiceHandler interface {
	Handle(DeleteParkingServiceParams, *models.User) middleware.Responder
}

// NewDeleteParkingService creates a new http.Handler for the delete parking service operation
func NewDeleteParkingService(ctx *middleware.Context, handler DeleteParkingServiceHandler) *DeleteParkingService {
	return &DeleteParkingService{Context: ctx, Handler: handler}
}

/*
	DeleteParkingService swagger:route DELETE /parking/{parking_id}/services/{service_id} parking deleteParkingService

Delete service
*/
type DeleteParkingService struct {
	Context *middleware.Context
	Handler DeleteParkingServiceHandler
}

func (o *DeleteParkingService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteParkingServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
