// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// GetParkingsURL generates an URL for the get parkings operation
type GetParkingsURL struct {
	City        *string
	Name        *string
	OwnerID     *string
	ParkingType *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetParkingsURL) WithBasePath(bp string) *GetParkingsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetParkingsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetParkingsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/parking"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var cityQ string
	if o.City != nil {
		cityQ = *o.City
	}
	if cityQ != "" {
		qs.Set("city", cityQ)
	}

	var nameQ string
	if o.Name != nil {
		nameQ = *o.Name
	}
	if nameQ != "" {
		qs.Set("name", nameQ)
	}

	var ownerIDQ string
	if o.OwnerID != nil {
		ownerIDQ = *o.OwnerID
	}
	if ownerIDQ != "" {
		qs.Set("owner_id", ownerIDQ)
	}

	var parkingTypeQ string
	if o.ParkingType != nil {
		parkingTypeQ = *o.ParkingType
	}
	if parkingTypeQ != "" {
		qs.Set("parking_type", parkingTypeQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetParkingsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetParkingsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetParkingsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetParkingsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetParkingsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetParkingsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
