// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// GetParkingServicesOKCode is the HTTP code returned for type GetParkingServicesOK
const GetParkingServicesOKCode int = 200

/*
GetParkingServicesOK successful operation

swagger:response getParkingServicesOK
*/
type GetParkingServicesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Service `json:"body,omitempty"`
}

// NewGetParkingServicesOK creates GetParkingServicesOK with default headers values
func NewGetParkingServicesOK() *GetParkingServicesOK {

	return &GetParkingServicesOK{}
}

// WithPayload adds the payload to the get parking services o k response
func (o *GetParkingServicesOK) WithPayload(payload []*models.Service) *GetParkingServicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parking services o k response
func (o *GetParkingServicesOK) SetPayload(payload []*models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingServicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Service, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetParkingServicesNotFoundCode is the HTTP code returned for type GetParkingServicesNotFound
const GetParkingServicesNotFoundCode int = 404

/*
GetParkingServicesNotFound Parking place not found

swagger:response getParkingServicesNotFound
*/
type GetParkingServicesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetParkingServicesNotFound creates GetParkingServicesNotFound with default headers values
func NewGetParkingServicesNotFound() *GetParkingServicesNotFound {

	return &GetParkingServicesNotFound{}
}

// WithPayload adds the payload to the get parking services not found response
func (o *GetParkingServicesNotFound) WithPayload(payload *models.Error) *GetParkingServicesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parking services not found response
func (o *GetParkingServicesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingServicesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
