// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetParkingByIDHandlerFunc turns a function with the right signature into a get parking by id handler
type GetParkingByIDHandlerFunc func(GetParkingByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetParkingByIDHandlerFunc) Handle(params GetParkingByIDParams) middleware.Responder {
	return fn(params)
}

// GetParkingByIDHandler interface for that can handle valid get parking by id params
type GetParkingByIDHandler interface {
	Handle(GetParkingByIDParams) middleware.Responder
}

// NewGetParkingByID creates a new http.Handler for the get parking by id operation
func NewGetParkingByID(ctx *middleware.Context, handler GetParkingByIDHandler) *GetParkingByID {
	return &GetParkingByID{Context: ctx, Handler: handler}
}

/*
	GetParkingByID swagger:route GET /parking/{parking_id} parking getParkingById

Get parking place info by id
*/
type GetParkingByID struct {
	Context *middleware.Context
	Handler GetParkingByIDHandler
}

func (o *GetParkingByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetParkingByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
