// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// GetParkingByIDOKCode is the HTTP code returned for type GetParkingByIDOK
const GetParkingByIDOKCode int = 200

/*
GetParkingByIDOK successful operation

swagger:response getParkingByIdOK
*/
type GetParkingByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ParkingPlace `json:"body,omitempty"`
}

// NewGetParkingByIDOK creates GetParkingByIDOK with default headers values
func NewGetParkingByIDOK() *GetParkingByIDOK {

	return &GetParkingByIDOK{}
}

// WithPayload adds the payload to the get parking by Id o k response
func (o *GetParkingByIDOK) WithPayload(payload *models.ParkingPlace) *GetParkingByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parking by Id o k response
func (o *GetParkingByIDOK) SetPayload(payload *models.ParkingPlace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetParkingByIDNotFoundCode is the HTTP code returned for type GetParkingByIDNotFound
const GetParkingByIDNotFoundCode int = 404

/*
GetParkingByIDNotFound Parking place not found

swagger:response getParkingByIdNotFound
*/
type GetParkingByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetParkingByIDNotFound creates GetParkingByIDNotFound with default headers values
func NewGetParkingByIDNotFound() *GetParkingByIDNotFound {

	return &GetParkingByIDNotFound{}
}

// WithPayload adds the payload to the get parking by Id not found response
func (o *GetParkingByIDNotFound) WithPayload(payload *models.Error) *GetParkingByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parking by Id not found response
func (o *GetParkingByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
