// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// GetParkingServiceHandlerFunc turns a function with the right signature into a get parking service handler
type GetParkingServiceHandlerFunc func(GetParkingServiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetParkingServiceHandlerFunc) Handle(params GetParkingServiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetParkingServiceHandler interface for that can handle valid get parking service params
type GetParkingServiceHandler interface {
	Handle(GetParkingServiceParams, *models.User) middleware.Responder
}

// NewGetParkingService creates a new http.Handler for the get parking service operation
func NewGetParkingService(ctx *middleware.Context, handler GetParkingServiceHandler) *GetParkingService {
	return &GetParkingService{Context: ctx, Handler: handler}
}

/*
	GetParkingService swagger:route GET /parking/{parking_id}/services/{service_id} parking getParkingService

Get service by ID
*/
type GetParkingService struct {
	Context *middleware.Context
	Handler GetParkingServiceHandler
}

func (o *GetParkingService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetParkingServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
