// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetParkingsHandlerFunc turns a function with the right signature into a get parkings handler
type GetParkingsHandlerFunc func(GetParkingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetParkingsHandlerFunc) Handle(params GetParkingsParams) middleware.Responder {
	return fn(params)
}

// GetParkingsHandler interface for that can handle valid get parkings params
type GetParkingsHandler interface {
	Handle(GetParkingsParams) middleware.Responder
}

// NewGetParkings creates a new http.Handler for the get parkings operation
func NewGetParkings(ctx *middleware.Context, handler GetParkingsHandler) *GetParkings {
	return &GetParkings{Context: ctx, Handler: handler}
}

/*
	GetParkings swagger:route GET /parking parking getParkings

Get suitable parking places
*/
type GetParkings struct {
	Context *middleware.Context
	Handler GetParkingsHandler
}

func (o *GetParkings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetParkingsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
