// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetParkingsParams creates a new GetParkingsParams object
//
// There are no default values defined in the spec.
func NewGetParkingsParams() GetParkingsParams {

	return GetParkingsParams{}
}

// GetParkingsParams contains all the bound params for the get parkings operation
// typically these are obtained from a http.Request
//
// swagger:parameters get_parkings
type GetParkingsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	City *string
	/*
	  In: query
	*/
	Name *string
	/*Filter parking places by owner ID (for owners to get their own parkings)
	  In: query
	*/
	OwnerID *string
	/*
	  In: query
	*/
	ParkingType *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetParkingsParams() beforehand.
func (o *GetParkingsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCity, qhkCity, _ := qs.GetOK("city")
	if err := o.bindCity(qCity, qhkCity, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	qOwnerID, qhkOwnerID, _ := qs.GetOK("owner_id")
	if err := o.bindOwnerID(qOwnerID, qhkOwnerID, route.Formats); err != nil {
		res = append(res, err)
	}

	qParkingType, qhkParkingType, _ := qs.GetOK("parking_type")
	if err := o.bindParkingType(qParkingType, qhkParkingType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCity binds and validates parameter City from query.
func (o *GetParkingsParams) bindCity(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.City = &raw

	return nil
}

// bindName binds and validates parameter Name from query.
func (o *GetParkingsParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Name = &raw

	return nil
}

// bindOwnerID binds and validates parameter OwnerID from query.
func (o *GetParkingsParams) bindOwnerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.OwnerID = &raw

	return nil
}

// bindParkingType binds and validates parameter ParkingType from query.
func (o *GetParkingsParams) bindParkingType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.ParkingType = &raw

	if err := o.validateParkingType(formats); err != nil {
		return err
	}

	return nil
}

// validateParkingType carries on validations for parameter ParkingType
func (o *GetParkingsParams) validateParkingType(formats strfmt.Registry) error {

	if err := validate.EnumCase("parking_type", "query", *o.ParkingType, []interface{}{"outdoor", "covered", "underground", "multi-level"}, true); err != nil {
		return err
	}

	return nil
}
