// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// GetParkingsOKCode is the HTTP code returned for type GetParkingsOK
const GetParkingsOKCode int = 200

/*
GetParkingsOK successful operation

swagger:response getParkingsOK
*/
type GetParkingsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ParkingPlace `json:"body,omitempty"`
}

// NewGetParkingsOK creates GetParkingsOK with default headers values
func NewGetParkingsOK() *GetParkingsOK {

	return &GetParkingsOK{}
}

// WithPayload adds the payload to the get parkings o k response
func (o *GetParkingsOK) WithPayload(payload []*models.ParkingPlace) *GetParkingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parkings o k response
func (o *GetParkingsOK) SetPayload(payload []*models.ParkingPlace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ParkingPlace, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetParkingsNotFoundCode is the HTTP code returned for type GetParkingsNotFound
const GetParkingsNotFoundCode int = 404

/*
GetParkingsNotFound Suitable parking places not found

swagger:response getParkingsNotFound
*/
type GetParkingsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetParkingsNotFound creates GetParkingsNotFound with default headers values
func NewGetParkingsNotFound() *GetParkingsNotFound {

	return &GetParkingsNotFound{}
}

// WithPayload adds the payload to the get parkings not found response
func (o *GetParkingsNotFound) WithPayload(payload *models.Error) *GetParkingsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parkings not found response
func (o *GetParkingsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
