// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// GetParkingServiceOKCode is the HTTP code returned for type GetParkingServiceOK
const GetParkingServiceOKCode int = 200

/*
GetParkingServiceOK successful operation

swagger:response getParkingServiceOK
*/
type GetParkingServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Service `json:"body,omitempty"`
}

// NewGetParkingServiceOK creates GetParkingServiceOK with default headers values
func NewGetParkingServiceOK() *GetParkingServiceOK {

	return &GetParkingServiceOK{}
}

// WithPayload adds the payload to the get parking service o k response
func (o *GetParkingServiceOK) WithPayload(payload *models.Service) *GetParkingServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parking service o k response
func (o *GetParkingServiceOK) SetPayload(payload *models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetParkingServiceNotFoundCode is the HTTP code returned for type GetParkingServiceNotFound
const GetParkingServiceNotFoundCode int = 404

/*
GetParkingServiceNotFound Service not found

swagger:response getParkingServiceNotFound
*/
type GetParkingServiceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetParkingServiceNotFound creates GetParkingServiceNotFound with default headers values
func NewGetParkingServiceNotFound() *GetParkingServiceNotFound {

	return &GetParkingServiceNotFound{}
}

// WithPayload adds the payload to the get parking service not found response
func (o *GetParkingServiceNotFound) WithPayload(payload *models.Error) *GetParkingServiceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parking service not found response
func (o *GetParkingServiceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetParkingServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
