// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetParkingByIDParams creates a new GetParkingByIDParams object
//
// There are no default values defined in the spec.
func NewGetParkingByIDParams() GetParkingByIDParams {

	return GetParkingByIDParams{}
}

// GetParkingByIDParams contains all the bound params for the get parking by id operation
// typically these are obtained from a http.Request
//
// swagger:parameters get_parking_by_id
type GetParkingByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of parking place to return
	  Required: true
	  In: path
	*/
	ParkingID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetParkingByIDParams() beforehand.
func (o *GetParkingByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rParkingID, rhkParkingID, _ := route.Params.GetOK("parking_id")
	if err := o.bindParkingID(rParkingID, rhkParkingID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParkingID binds and validates parameter ParkingID from path.
func (o *GetParkingByIDParams) bindParkingID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("parking_id", "path", "int64", raw)
	}
	o.ParkingID = value

	return nil
}
