// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// GetParkingServicesHandlerFunc turns a function with the right signature into a get parking services handler
type GetParkingServicesHandlerFunc func(GetParkingServicesParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetParkingServicesHandlerFunc) Handle(params GetParkingServicesParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetParkingServicesHandler interface for that can handle valid get parking services params
type GetParkingServicesHandler interface {
	Handle(GetParkingServicesParams, *models.User) middleware.Responder
}

// NewGetParkingServices creates a new http.Handler for the get parking services operation
func NewGetParkingServices(ctx *middleware.Context, handler GetParkingServicesHandler) *GetParkingServices {
	return &GetParkingServices{Context: ctx, Handler: handler}
}

/*
	GetParkingServices swagger:route GET /parking/{parking_id}/services parking getParkingServices

Get services for a parking place
*/
type GetParkingServices struct {
	Context *middleware.Context
	Handler GetParkingServicesHandler
}

func (o *GetParkingServices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetParkingServicesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
