// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// UpdateParkingHandlerFunc turns a function with the right signature into a update parking handler
type UpdateParkingHandlerFunc func(UpdateParkingParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateParkingHandlerFunc) Handle(params UpdateParkingParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateParkingHandler interface for that can handle valid update parking params
type UpdateParkingHandler interface {
	Handle(UpdateParkingParams, *models.User) middleware.Responder
}

// NewUpdateParking creates a new http.Handler for the update parking operation
func NewUpdateParking(ctx *middleware.Context, handler UpdateParkingHandler) *UpdateParking {
	return &UpdateParking{Context: ctx, Handler: handler}
}

/*
	UpdateParking swagger:route PUT /parking/{parking_id} parking updateParking

Update parking place
*/
type UpdateParking struct {
	Context *middleware.Context
	Handler UpdateParkingHandler
}

func (o *UpdateParking) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateParkingParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
