// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// UpdateParkingServiceURL generates an URL for the update parking service operation
type UpdateParkingServiceURL struct {
	ParkingID int64
	ServiceID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateParkingServiceURL) WithBasePath(bp string) *UpdateParkingServiceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateParkingServiceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *UpdateParkingServiceURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/parking/{parking_id}/services/{service_id}"

	parkingID := swag.FormatInt64(o.ParkingID)
	if parkingID != "" {
		_path = strings.Replace(_path, "{parking_id}", parkingID, -1)
	} else {
		return nil, errors.New("parkingId is required on UpdateParkingServiceURL")
	}

	serviceID := swag.FormatInt64(o.ServiceID)
	if serviceID != "" {
		_path = strings.Replace(_path, "{service_id}", serviceID, -1)
	} else {
		return nil, errors.New("serviceId is required on UpdateParkingServiceURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *UpdateParkingServiceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *UpdateParkingServiceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *UpdateParkingServiceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on UpdateParkingServiceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on UpdateParkingServiceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *UpdateParkingServiceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
