// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// UpdateParkingOKCode is the HTTP code returned for type UpdateParkingOK
const UpdateParkingOKCode int = 200

/*
UpdateParkingOK successful operation

swagger:response updateParkingOK
*/
type UpdateParkingOK struct {

	/*
	  In: Body
	*/
	Payload *models.ParkingPlace `json:"body,omitempty"`
}

// NewUpdateParkingOK creates UpdateParkingOK with default headers values
func NewUpdateParkingOK() *UpdateParkingOK {

	return &UpdateParkingOK{}
}

// WithPayload adds the payload to the update parking o k response
func (o *UpdateParkingOK) WithPayload(payload *models.ParkingPlace) *UpdateParkingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking o k response
func (o *UpdateParkingOK) SetPayload(payload *models.ParkingPlace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateParkingBadRequestCode is the HTTP code returned for type UpdateParkingBadRequest
const UpdateParkingBadRequestCode int = 400

/*
UpdateParkingBadRequest Incorrect data

swagger:response updateParkingBadRequest
*/
type UpdateParkingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateParkingBadRequest creates UpdateParkingBadRequest with default headers values
func NewUpdateParkingBadRequest() *UpdateParkingBadRequest {

	return &UpdateParkingBadRequest{}
}

// WithPayload adds the payload to the update parking bad request response
func (o *UpdateParkingBadRequest) WithPayload(payload *models.Error) *UpdateParkingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking bad request response
func (o *UpdateParkingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateParkingForbiddenCode is the HTTP code returned for type UpdateParkingForbidden
const UpdateParkingForbiddenCode int = 403

/*
UpdateParkingForbidden No access

swagger:response updateParkingForbidden
*/
type UpdateParkingForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateParkingForbidden creates UpdateParkingForbidden with default headers values
func NewUpdateParkingForbidden() *UpdateParkingForbidden {

	return &UpdateParkingForbidden{}
}

// WithPayload adds the payload to the update parking forbidden response
func (o *UpdateParkingForbidden) WithPayload(payload *models.Error) *UpdateParkingForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking forbidden response
func (o *UpdateParkingForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateParkingNotFoundCode is the HTTP code returned for type UpdateParkingNotFound
const UpdateParkingNotFoundCode int = 404

/*
UpdateParkingNotFound No such element

swagger:response updateParkingNotFound
*/
type UpdateParkingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateParkingNotFound creates UpdateParkingNotFound with default headers values
func NewUpdateParkingNotFound() *UpdateParkingNotFound {

	return &UpdateParkingNotFound{}
}

// WithPayload adds the payload to the update parking not found response
func (o *UpdateParkingNotFound) WithPayload(payload *models.Error) *UpdateParkingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking not found response
func (o *UpdateParkingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
