// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// UpdateParkingServiceOKCode is the HTTP code returned for type UpdateParkingServiceOK
const UpdateParkingServiceOKCode int = 200

/*
UpdateParkingServiceOK successful operation

swagger:response updateParkingServiceOK
*/
type UpdateParkingServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Service `json:"body,omitempty"`
}

// NewUpdateParkingServiceOK creates UpdateParkingServiceOK with default headers values
func NewUpdateParkingServiceOK() *UpdateParkingServiceOK {

	return &UpdateParkingServiceOK{}
}

// WithPayload adds the payload to the update parking service o k response
func (o *UpdateParkingServiceOK) WithPayload(payload *models.Service) *UpdateParkingServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking service o k response
func (o *UpdateParkingServiceOK) SetPayload(payload *models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateParkingServiceBadRequestCode is the HTTP code returned for type UpdateParkingServiceBadRequest
const UpdateParkingServiceBadRequestCode int = 400

/*
UpdateParkingServiceBadRequest Incorrect data

swagger:response updateParkingServiceBadRequest
*/
type UpdateParkingServiceBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateParkingServiceBadRequest creates UpdateParkingServiceBadRequest with default headers values
func NewUpdateParkingServiceBadRequest() *UpdateParkingServiceBadRequest {

	return &UpdateParkingServiceBadRequest{}
}

// WithPayload adds the payload to the update parking service bad request response
func (o *UpdateParkingServiceBadRequest) WithPayload(payload *models.Error) *UpdateParkingServiceBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking service bad request response
func (o *UpdateParkingServiceBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateParkingServiceForbiddenCode is the HTTP code returned for type UpdateParkingServiceForbidden
const UpdateParkingServiceForbiddenCode int = 403

/*
UpdateParkingServiceForbidden No access

swagger:response updateParkingServiceForbidden
*/
type UpdateParkingServiceForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateParkingServiceForbidden creates UpdateParkingServiceForbidden with default headers values
func NewUpdateParkingServiceForbidden() *UpdateParkingServiceForbidden {

	return &UpdateParkingServiceForbidden{}
}

// WithPayload adds the payload to the update parking service forbidden response
func (o *UpdateParkingServiceForbidden) WithPayload(payload *models.Error) *UpdateParkingServiceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking service forbidden response
func (o *UpdateParkingServiceForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateParkingServiceNotFoundCode is the HTTP code returned for type UpdateParkingServiceNotFound
const UpdateParkingServiceNotFoundCode int = 404

/*
UpdateParkingServiceNotFound Service not found

swagger:response updateParkingServiceNotFound
*/
type UpdateParkingServiceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateParkingServiceNotFound creates UpdateParkingServiceNotFound with default headers values
func NewUpdateParkingServiceNotFound() *UpdateParkingServiceNotFound {

	return &UpdateParkingServiceNotFound{}
}

// WithPayload adds the payload to the update parking service not found response
func (o *UpdateParkingServiceNotFound) WithPayload(payload *models.Error) *UpdateParkingServiceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update parking service not found response
func (o *UpdateParkingServiceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateParkingServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
