// Code generated by go-swagger; DO NOT EDIT.

package parking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/parking/internal/models"
)

// UpdateParkingServiceHandlerFunc turns a function with the right signature into a update parking service handler
type UpdateParkingServiceHandlerFunc func(UpdateParkingServiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateParkingServiceHandlerFunc) Handle(params UpdateParkingServiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateParkingServiceHandler interface for that can handle valid update parking service params
type UpdateParkingServiceHandler interface {
	Handle(UpdateParkingServiceParams, *models.User) middleware.Responder
}

// NewUpdateParkingService creates a new http.Handler for the update parking service operation
func NewUpdateParkingService(ctx *middleware.Context, handler UpdateParkingServiceHandler) *UpdateParkingService {
	return &UpdateParkingService{Context: ctx, Handler: handler}
}

/*
	UpdateParkingService swagger:route PUT /parking/{parking_id}/services/{service_id} parking updateParkingService

Update service
*/
type UpdateParkingService struct {
	Context *middleware.Context
	Handler UpdateParkingServiceHandler
}

func (o *UpdateParkingService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateParkingServiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
