// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ParkingPlace parking place
//
// swagger:model ParkingPlace
type ParkingPlace struct {

	// address
	// Example: Red Square №1
	// Required: true
	Address *string `json:"address"`

	// total number of parking spots
	Capacity int64 `json:"capacity,omitempty"`

	// city
	// Example: Moscow
	// Required: true
	City *string `json:"city"`

	// hourly parking rate
	HourlyRate int64 `json:"hourly_rate,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	// Example: Central Parking
	// Required: true
	Name *string `json:"name"`

	// owner id
	OwnerID string `json:"owner_id,omitempty"`

	// type of parking facility
	// Enum: ["outdoor","covered","underground","multi-level"]
	ParkingType string `json:"parking_type,omitempty"`
}

// Validate validates this parking place
func (m *ParkingPlace) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParkingType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ParkingPlace) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *ParkingPlace) validateCity(formats strfmt.Registry) error {

	if err := validate.Required("city", "body", m.City); err != nil {
		return err
	}

	return nil
}

func (m *ParkingPlace) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var parkingPlaceTypeParkingTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["outdoor","covered","underground","multi-level"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		parkingPlaceTypeParkingTypePropEnum = append(parkingPlaceTypeParkingTypePropEnum, v)
	}
}

const (

	// ParkingPlaceParkingTypeOutdoor captures enum value "outdoor"
	ParkingPlaceParkingTypeOutdoor string = "outdoor"

	// ParkingPlaceParkingTypeCovered captures enum value "covered"
	ParkingPlaceParkingTypeCovered string = "covered"

	// ParkingPlaceParkingTypeUnderground captures enum value "underground"
	ParkingPlaceParkingTypeUnderground string = "underground"

	// ParkingPlaceParkingTypeMultiDashLevel captures enum value "multi-level"
	ParkingPlaceParkingTypeMultiDashLevel string = "multi-level"
)

// prop value enum
func (m *ParkingPlace) validateParkingTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, parkingPlaceTypeParkingTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ParkingPlace) validateParkingType(formats strfmt.Registry) error {
	if swag.IsZero(m.ParkingType) { // not required
		return nil
	}

	// value enum
	if err := m.validateParkingTypeEnum("parking_type", "body", m.ParkingType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this parking place based on context it is used
func (m *ParkingPlace) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParkingPlace) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParkingPlace) UnmarshalBinary(b []byte) error {
	var res ParkingPlace
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
