// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreatePromocodeRequest create promocode request
//
// swagger:model CreatePromocodeRequest
type CreatePromocodeRequest struct {

	// Promocode value in cents
	// Required: true
	Amount *int64 `json:"amount"`

	// Custom promocode (optional, will be generated if not provided)
	Code string `json:"code,omitempty"`

	// Expiration date (optional)
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires_at,omitempty"`

	// Maximum number of times this promocode can be used
	// Required: true
	MaxUses *int64 `json:"max_uses"`
}

// Validate validates this create promocode request
func (m *CreatePromocodeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxUses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreatePromocodeRequest) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *CreatePromocodeRequest) validateExpiresAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires_at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CreatePromocodeRequest) validateMaxUses(formats strfmt.Registry) error {

	if err := validate.Required("max_uses", "body", m.MaxUses); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create promocode request based on context it is used
func (m *CreatePromocodeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreatePromocodeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatePromocodeRequest) UnmarshalBinary(b []byte) error {
	var res CreatePromocodeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
