// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PromocodeInfo promocode info
//
// swagger:model PromocodeInfo
type PromocodeInfo struct {

	// Promocode value in cents
	Amount int64 `json:"amount,omitempty"`

	// code
	Code string `json:"code,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires_at,omitempty"`

	// Whether promocode is still valid and can be used
	IsActive bool `json:"is_active,omitempty"`

	// max uses
	MaxUses int64 `json:"max_uses,omitempty"`

	// remaining uses
	RemainingUses int64 `json:"remaining_uses,omitempty"`

	// used count
	UsedCount int64 `json:"used_count,omitempty"`
}

// Validate validates this promocode info
func (m *PromocodeInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PromocodeInfo) validateExpiresAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires_at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this promocode info based on context it is used
func (m *PromocodeInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PromocodeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PromocodeInfo) UnmarshalBinary(b []byte) error {
	var res PromocodeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
