// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransactionResponse transaction response
//
// swagger:model TransactionResponse
type TransactionResponse struct {

	// message
	Message string `json:"message,omitempty"`

	// status
	// Enum: ["completed","failed"]
	Status string `json:"status,omitempty"`

	// transaction id
	TransactionID int64 `json:"transaction_id,omitempty"`
}

// Validate validates this transaction response
func (m *TransactionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var transactionResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		transactionResponseTypeStatusPropEnum = append(transactionResponseTypeStatusPropEnum, v)
	}
}

const (

	// TransactionResponseStatusCompleted captures enum value "completed"
	TransactionResponseStatusCompleted string = "completed"

	// TransactionResponseStatusFailed captures enum value "failed"
	TransactionResponseStatusFailed string = "failed"
)

// prop value enum
func (m *TransactionResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, transactionResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TransactionResponse) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this transaction response based on context it is used
func (m *TransactionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionResponse) UnmarshalBinary(b []byte) error {
	var res TransactionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
