// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Transaction transaction
//
// swagger:model Transaction
type Transaction struct {

	// Transaction amount in cents (negative for charges, positive for payments)
	Amount int64 `json:"amount,omitempty"`

	// booking id
	BookingID int64 `json:"booking_id,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// status
	// Enum: ["pending","completed","failed","canceled"]
	Status string `json:"status,omitempty"`

	// transaction type
	// Enum: ["charge","payment","refund","promocode_activate","promocode_generate"]
	TransactionType string `json:"transaction_type,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this transaction
func (m *Transaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Transaction) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var transactionTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","completed","failed","canceled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		transactionTypeStatusPropEnum = append(transactionTypeStatusPropEnum, v)
	}
}

const (

	// TransactionStatusPending captures enum value "pending"
	TransactionStatusPending string = "pending"

	// TransactionStatusCompleted captures enum value "completed"
	TransactionStatusCompleted string = "completed"

	// TransactionStatusFailed captures enum value "failed"
	TransactionStatusFailed string = "failed"

	// TransactionStatusCanceled captures enum value "canceled"
	TransactionStatusCanceled string = "canceled"
)

// prop value enum
func (m *Transaction) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, transactionTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Transaction) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

var transactionTypeTransactionTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["charge","payment","refund","promocode_activate","promocode_generate"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		transactionTypeTransactionTypePropEnum = append(transactionTypeTransactionTypePropEnum, v)
	}
}

const (

	// TransactionTransactionTypeCharge captures enum value "charge"
	TransactionTransactionTypeCharge string = "charge"

	// TransactionTransactionTypePayment captures enum value "payment"
	TransactionTransactionTypePayment string = "payment"

	// TransactionTransactionTypeRefund captures enum value "refund"
	TransactionTransactionTypeRefund string = "refund"

	// TransactionTransactionTypePromocodeActivate captures enum value "promocode_activate"
	TransactionTransactionTypePromocodeActivate string = "promocode_activate"

	// TransactionTransactionTypePromocodeGenerate captures enum value "promocode_generate"
	TransactionTransactionTypePromocodeGenerate string = "promocode_generate"
)

// prop value enum
func (m *Transaction) validateTransactionTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, transactionTypeTransactionTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Transaction) validateTransactionType(formats strfmt.Registry) error {
	if swag.IsZero(m.TransactionType) { // not required
		return nil
	}

	// value enum
	if err := m.validateTransactionTypeEnum("transaction_type", "body", m.TransactionType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this transaction based on context it is used
func (m *Transaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Transaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Transaction) UnmarshalBinary(b []byte) error {
	var res Transaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
