// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransactionRequest transaction request
//
// swagger:model TransactionRequest
type TransactionRequest struct {

	// Amount in cents
	// Required: true
	Amount *int64 `json:"amount"`

	// booking id
	// Required: true
	BookingID *int64 `json:"booking_id"`

	// driver id
	// Required: true
	DriverID *string `json:"driver_id"`

	// owner id
	// Required: true
	OwnerID *string `json:"owner_id"`
}

// Validate validates this transaction request
func (m *TransactionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBookingID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDriverID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwnerID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransactionRequest) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *TransactionRequest) validateBookingID(formats strfmt.Registry) error {

	if err := validate.Required("booking_id", "body", m.BookingID); err != nil {
		return err
	}

	return nil
}

func (m *TransactionRequest) validateDriverID(formats strfmt.Registry) error {

	if err := validate.Required("driver_id", "body", m.DriverID); err != nil {
		return err
	}

	return nil
}

func (m *TransactionRequest) validateOwnerID(formats strfmt.Registry) error {

	if err := validate.Required("owner_id", "body", m.OwnerID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this transaction request based on context it is used
func (m *TransactionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransactionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionRequest) UnmarshalBinary(b []byte) error {
	var res TransactionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
