// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// ActivatePromocodeOKCode is the HTTP code returned for type ActivatePromocodeOK
const ActivatePromocodeOKCode int = 200

/*
ActivatePromocodeOK successful operation

swagger:response activatePromocodeOK
*/
type ActivatePromocodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Balance `json:"body,omitempty"`
}

// NewActivatePromocodeOK creates ActivatePromocodeOK with default headers values
func NewActivatePromocodeOK() *ActivatePromocodeOK {

	return &ActivatePromocodeOK{}
}

// WithPayload adds the payload to the activate promocode o k response
func (o *ActivatePromocodeOK) WithPayload(payload *models.Balance) *ActivatePromocodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activate promocode o k response
func (o *ActivatePromocodeOK) SetPayload(payload *models.Balance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivatePromocodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ActivatePromocodeBadRequestCode is the HTTP code returned for type ActivatePromocodeBadRequest
const ActivatePromocodeBadRequestCode int = 400

/*
ActivatePromocodeBadRequest Invalid or expired promocode

swagger:response activatePromocodeBadRequest
*/
type ActivatePromocodeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewActivatePromocodeBadRequest creates ActivatePromocodeBadRequest with default headers values
func NewActivatePromocodeBadRequest() *ActivatePromocodeBadRequest {

	return &ActivatePromocodeBadRequest{}
}

// WithPayload adds the payload to the activate promocode bad request response
func (o *ActivatePromocodeBadRequest) WithPayload(payload *models.Error) *ActivatePromocodeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activate promocode bad request response
func (o *ActivatePromocodeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivatePromocodeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ActivatePromocodeNotFoundCode is the HTTP code returned for type ActivatePromocodeNotFound
const ActivatePromocodeNotFoundCode int = 404

/*
ActivatePromocodeNotFound Promocode not found

swagger:response activatePromocodeNotFound
*/
type ActivatePromocodeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewActivatePromocodeNotFound creates ActivatePromocodeNotFound with default headers values
func NewActivatePromocodeNotFound() *ActivatePromocodeNotFound {

	return &ActivatePromocodeNotFound{}
}

// WithPayload adds the payload to the activate promocode not found response
func (o *ActivatePromocodeNotFound) WithPayload(payload *models.Error) *ActivatePromocodeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activate promocode not found response
func (o *ActivatePromocodeNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivatePromocodeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
