// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// ActivatePromocodeHandlerFunc turns a function with the right signature into a activate promocode handler
type ActivatePromocodeHandlerFunc func(ActivatePromocodeParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn ActivatePromocodeHandlerFunc) Handle(params ActivatePromocodeParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// ActivatePromocodeHandler interface for that can handle valid activate promocode params
type ActivatePromocodeHandler interface {
	Handle(ActivatePromocodeParams, *models.User) middleware.Responder
}

// NewActivatePromocode creates a new http.Handler for the activate promocode operation
func NewActivatePromocode(ctx *middleware.Context, handler ActivatePromocodeHandler) *ActivatePromocode {
	return &ActivatePromocode{Context: ctx, Handler: handler}
}

/*
	ActivatePromocode swagger:route POST /payment/promocode/activate driver owner activatePromocode

Activate promocode to add balance
*/
type ActivatePromocode struct {
	Context *middleware.Context
	Handler ActivatePromocodeHandler
}

func (o *ActivatePromocode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewActivatePromocodeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
