// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// NewActivatePromocodeParams creates a new ActivatePromocodeParams object
//
// There are no default values defined in the spec.
func NewActivatePromocodeParams() ActivatePromocodeParams {

	return ActivatePromocodeParams{}
}

// ActivatePromocodeParams contains all the bound params for the activate promocode operation
// typically these are obtained from a http.Request
//
// swagger:parameters activate_promocode
type ActivatePromocodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Object *models.ActivatePromocodeRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewActivatePromocodeParams() beforehand.
func (o *ActivatePromocodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ActivatePromocodeRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("object", "body", ""))
			} else {
				res = append(res, errors.NewParseError("object", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Object = &body
			}
		}
	} else {
		res = append(res, errors.Required("object", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
