// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// DepositHandlerFunc turns a function with the right signature into a deposit handler
type DepositHandlerFunc func(DepositParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DepositHandlerFunc) Handle(params DepositParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DepositHandler interface for that can handle valid deposit params
type DepositHandler interface {
	Handle(DepositParams, *models.User) middleware.Responder
}

// NewDeposit creates a new http.Handler for the deposit operation
func NewDeposit(ctx *middleware.Context, handler DepositHandler) *Deposit {
	return &Deposit{Context: ctx, Handler: handler}
}

/*
	Deposit swagger:route POST /payment/deposit driver owner deposit

Deposit money to account
*/
type Deposit struct {
	Context *middleware.Context
	Handler DepositHandler
}

func (o *Deposit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDepositParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
