// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// DepositOKCode is the HTTP code returned for type DepositOK
const DepositOKCode int = 200

/*
DepositOK successful operation

swagger:response depositOK
*/
type DepositOK struct {

	/*
	  In: Body
	*/
	Payload *models.Balance `json:"body,omitempty"`
}

// NewDepositOK creates DepositOK with default headers values
func NewDepositOK() *DepositOK {

	return &DepositOK{}
}

// WithPayload adds the payload to the deposit o k response
func (o *DepositOK) WithPayload(payload *models.Balance) *DepositOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deposit o k response
func (o *DepositOK) SetPayload(payload *models.Balance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DepositOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DepositBadRequestCode is the HTTP code returned for type DepositBadRequest
const DepositBadRequestCode int = 400

/*
DepositBadRequest Invalid request

swagger:response depositBadRequest
*/
type DepositBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDepositBadRequest creates DepositBadRequest with default headers values
func NewDepositBadRequest() *DepositBadRequest {

	return &DepositBadRequest{}
}

// WithPayload adds the payload to the deposit bad request response
func (o *DepositBadRequest) WithPayload(payload *models.Error) *DepositBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deposit bad request response
func (o *DepositBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DepositBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
