// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GeneratePromocodeOKCode is the HTTP code returned for type GeneratePromocodeOK
const GeneratePromocodeOKCode int = 200

/*
GeneratePromocodeOK successful operation

swagger:response generatePromocodeOK
*/
type GeneratePromocodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.PromocodeResponse `json:"body,omitempty"`
}

// NewGeneratePromocodeOK creates GeneratePromocodeOK with default headers values
func NewGeneratePromocodeOK() *GeneratePromocodeOK {

	return &GeneratePromocodeOK{}
}

// WithPayload adds the payload to the generate promocode o k response
func (o *GeneratePromocodeOK) WithPayload(payload *models.PromocodeResponse) *GeneratePromocodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the generate promocode o k response
func (o *GeneratePromocodeOK) SetPayload(payload *models.PromocodeResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeneratePromocodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeneratePromocodeBadRequestCode is the HTTP code returned for type GeneratePromocodeBadRequest
const GeneratePromocodeBadRequestCode int = 400

/*
GeneratePromocodeBadRequest Insufficient funds or invalid request

swagger:response generatePromocodeBadRequest
*/
type GeneratePromocodeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGeneratePromocodeBadRequest creates GeneratePromocodeBadRequest with default headers values
func NewGeneratePromocodeBadRequest() *GeneratePromocodeBadRequest {

	return &GeneratePromocodeBadRequest{}
}

// WithPayload adds the payload to the generate promocode bad request response
func (o *GeneratePromocodeBadRequest) WithPayload(payload *models.Error) *GeneratePromocodeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the generate promocode bad request response
func (o *GeneratePromocodeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeneratePromocodeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GeneratePromocodeInternalServerErrorCode is the HTTP code returned for type GeneratePromocodeInternalServerError
const GeneratePromocodeInternalServerErrorCode int = 500

/*
GeneratePromocodeInternalServerError Internal server error

swagger:response generatePromocodeInternalServerError
*/
type GeneratePromocodeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGeneratePromocodeInternalServerError creates GeneratePromocodeInternalServerError with default headers values
func NewGeneratePromocodeInternalServerError() *GeneratePromocodeInternalServerError {

	return &GeneratePromocodeInternalServerError{}
}

// WithPayload adds the payload to the generate promocode internal server error response
func (o *GeneratePromocodeInternalServerError) WithPayload(payload *models.Error) *GeneratePromocodeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the generate promocode internal server error response
func (o *GeneratePromocodeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GeneratePromocodeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
