// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GeneratePromocodeHandlerFunc turns a function with the right signature into a generate promocode handler
type GeneratePromocodeHandlerFunc func(GeneratePromocodeParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GeneratePromocodeHandlerFunc) Handle(params GeneratePromocodeParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GeneratePromocodeHandler interface for that can handle valid generate promocode params
type GeneratePromocodeHandler interface {
	Handle(GeneratePromocodeParams, *models.User) middleware.Responder
}

// NewGeneratePromocode creates a new http.Handler for the generate promocode operation
func NewGeneratePromocode(ctx *middleware.Context, handler GeneratePromocodeHandler) *GeneratePromocode {
	return &GeneratePromocode{Context: ctx, Handler: handler}
}

/*
	GeneratePromocode swagger:route POST /payment/promocode/generate driver owner generatePromocode

Generate promocode from user balance
*/
type GeneratePromocode struct {
	Context *middleware.Context
	Handler GeneratePromocodeHandler
}

func (o *GeneratePromocode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGeneratePromocodeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
