// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GetTransactionsOKCode is the HTTP code returned for type GetTransactionsOK
const GetTransactionsOKCode int = 200

/*
GetTransactionsOK successful operation

swagger:response getTransactionsOK
*/
type GetTransactionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Transaction `json:"body,omitempty"`
}

// NewGetTransactionsOK creates GetTransactionsOK with default headers values
func NewGetTransactionsOK() *GetTransactionsOK {

	return &GetTransactionsOK{}
}

// WithPayload adds the payload to the get transactions o k response
func (o *GetTransactionsOK) WithPayload(payload []*models.Transaction) *GetTransactionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions o k response
func (o *GetTransactionsOK) SetPayload(payload []*models.Transaction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Transaction, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTransactionsForbiddenCode is the HTTP code returned for type GetTransactionsForbidden
const GetTransactionsForbiddenCode int = 403

/*
GetTransactionsForbidden No access

swagger:response getTransactionsForbidden
*/
type GetTransactionsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTransactionsForbidden creates GetTransactionsForbidden with default headers values
func NewGetTransactionsForbidden() *GetTransactionsForbidden {

	return &GetTransactionsForbidden{}
}

// WithPayload adds the payload to the get transactions forbidden response
func (o *GetTransactionsForbidden) WithPayload(payload *models.Error) *GetTransactionsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions forbidden response
func (o *GetTransactionsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTransactionsInternalServerErrorCode is the HTTP code returned for type GetTransactionsInternalServerError
const GetTransactionsInternalServerErrorCode int = 500

/*
GetTransactionsInternalServerError Internal server error

swagger:response getTransactionsInternalServerError
*/
type GetTransactionsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTransactionsInternalServerError creates GetTransactionsInternalServerError with default headers values
func NewGetTransactionsInternalServerError() *GetTransactionsInternalServerError {

	return &GetTransactionsInternalServerError{}
}

// WithPayload adds the payload to the get transactions internal server error response
func (o *GetTransactionsInternalServerError) WithPayload(payload *models.Error) *GetTransactionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions internal server error response
func (o *GetTransactionsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
