// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GetTransactionsHandlerFunc turns a function with the right signature into a get transactions handler
type GetTransactionsHandlerFunc func(GetTransactionsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransactionsHandlerFunc) Handle(params GetTransactionsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetTransactionsHandler interface for that can handle valid get transactions params
type GetTransactionsHandler interface {
	Handle(GetTransactionsParams, *models.User) middleware.Responder
}

// NewGetTransactions creates a new http.Handler for the get transactions operation
func NewGetTransactions(ctx *middleware.Context, handler GetTransactionsHandler) *GetTransactions {
	return &GetTransactions{Context: ctx, Handler: handler}
}

/*
	GetTransactions swagger:route GET /payment/transactions driver owner getTransactions

Get user transactions
*/
type GetTransactions struct {
	Context *middleware.Context
	Handler GetTransactionsHandler
}

func (o *GetTransactions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTransactionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
