// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GetBalanceHandlerFunc turns a function with the right signature into a get balance handler
type GetBalanceHandlerFunc func(GetBalanceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBalanceHandlerFunc) Handle(params GetBalanceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetBalanceHandler interface for that can handle valid get balance params
type GetBalanceHandler interface {
	Handle(GetBalanceParams, *models.User) middleware.Responder
}

// NewGetBalance creates a new http.Handler for the get balance operation
func NewGetBalance(ctx *middleware.Context, handler GetBalanceHandler) *GetBalance {
	return &GetBalance{Context: ctx, Handler: handler}
}

/*
	GetBalance swagger:route GET /payment/balance driver owner getBalance

Get user balance
*/
type GetBalance struct {
	Context *middleware.Context
	Handler GetBalanceHandler
}

func (o *GetBalance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBalanceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
