// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GetPromocodeOKCode is the HTTP code returned for type GetPromocodeOK
const GetPromocodeOKCode int = 200

/*
GetPromocodeOK successful operation

swagger:response getPromocodeOK
*/
type GetPromocodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.PromocodeInfo `json:"body,omitempty"`
}

// NewGetPromocodeOK creates GetPromocodeOK with default headers values
func NewGetPromocodeOK() *GetPromocodeOK {

	return &GetPromocodeOK{}
}

// WithPayload adds the payload to the get promocode o k response
func (o *GetPromocodeOK) WithPayload(payload *models.PromocodeInfo) *GetPromocodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get promocode o k response
func (o *GetPromocodeOK) SetPayload(payload *models.PromocodeInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPromocodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPromocodeNotFoundCode is the HTTP code returned for type GetPromocodeNotFound
const GetPromocodeNotFoundCode int = 404

/*
GetPromocodeNotFound Promocode not found

swagger:response getPromocodeNotFound
*/
type GetPromocodeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPromocodeNotFound creates GetPromocodeNotFound with default headers values
func NewGetPromocodeNotFound() *GetPromocodeNotFound {

	return &GetPromocodeNotFound{}
}

// WithPayload adds the payload to the get promocode not found response
func (o *GetPromocodeNotFound) WithPayload(payload *models.Error) *GetPromocodeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get promocode not found response
func (o *GetPromocodeNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPromocodeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
