// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GetBalanceOKCode is the HTTP code returned for type GetBalanceOK
const GetBalanceOKCode int = 200

/*
GetBalanceOK successful operation

swagger:response getBalanceOK
*/
type GetBalanceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Balance `json:"body,omitempty"`
}

// NewGetBalanceOK creates GetBalanceOK with default headers values
func NewGetBalanceOK() *GetBalanceOK {

	return &GetBalanceOK{}
}

// WithPayload adds the payload to the get balance o k response
func (o *GetBalanceOK) WithPayload(payload *models.Balance) *GetBalanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get balance o k response
func (o *GetBalanceOK) SetPayload(payload *models.Balance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBalanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBalanceNotFoundCode is the HTTP code returned for type GetBalanceNotFound
const GetBalanceNotFoundCode int = 404

/*
GetBalanceNotFound Balance not found

swagger:response getBalanceNotFound
*/
type GetBalanceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBalanceNotFound creates GetBalanceNotFound with default headers values
func NewGetBalanceNotFound() *GetBalanceNotFound {

	return &GetBalanceNotFound{}
}

// WithPayload adds the payload to the get balance not found response
func (o *GetBalanceNotFound) WithPayload(payload *models.Error) *GetBalanceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get balance not found response
func (o *GetBalanceNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBalanceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBalanceInternalServerErrorCode is the HTTP code returned for type GetBalanceInternalServerError
const GetBalanceInternalServerErrorCode int = 500

/*
GetBalanceInternalServerError Internal server error

swagger:response getBalanceInternalServerError
*/
type GetBalanceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBalanceInternalServerError creates GetBalanceInternalServerError with default headers values
func NewGetBalanceInternalServerError() *GetBalanceInternalServerError {

	return &GetBalanceInternalServerError{}
}

// WithPayload adds the payload to the get balance internal server error response
func (o *GetBalanceInternalServerError) WithPayload(payload *models.Error) *GetBalanceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get balance internal server error response
func (o *GetBalanceInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBalanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
