// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// GetPromocodeHandlerFunc turns a function with the right signature into a get promocode handler
type GetPromocodeHandlerFunc func(GetPromocodeParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPromocodeHandlerFunc) Handle(params GetPromocodeParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetPromocodeHandler interface for that can handle valid get promocode params
type GetPromocodeHandler interface {
	Handle(GetPromocodeParams, *models.User) middleware.Responder
}

// NewGetPromocode creates a new http.Handler for the get promocode operation
func NewGetPromocode(ctx *middleware.Context, handler GetPromocodeHandler) *GetPromocode {
	return &GetPromocode{Context: ctx, Handler: handler}
}

/*
	GetPromocode swagger:route GET /payment/promocode/{code} driver owner admin getPromocode

Get promocode information
*/
type GetPromocode struct {
	Context *middleware.Context
	Handler GetPromocodeHandler
}

func (o *GetPromocode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPromocodeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
