// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// WithdrawHandlerFunc turns a function with the right signature into a withdraw handler
type WithdrawHandlerFunc func(WithdrawParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn WithdrawHandlerFunc) Handle(params WithdrawParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// WithdrawHandler interface for that can handle valid withdraw params
type WithdrawHandler interface {
	Handle(WithdrawParams, *models.User) middleware.Responder
}

// NewWithdraw creates a new http.Handler for the withdraw operation
func NewWithdraw(ctx *middleware.Context, handler WithdrawHandler) *Withdraw {
	return &Withdraw{Context: ctx, Handler: handler}
}

/*
	Withdraw swagger:route POST /payment/withdraw driver owner withdraw

Withdraw money from account
*/
type Withdraw struct {
	Context *middleware.Context
	Handler WithdrawHandler
}

func (o *Withdraw) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewWithdrawParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
