// Code generated by go-swagger; DO NOT EDIT.

package driver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/parking_net/payment/internal/models"
)

// WithdrawOKCode is the HTTP code returned for type WithdrawOK
const WithdrawOKCode int = 200

/*
WithdrawOK successful operation

swagger:response withdrawOK
*/
type WithdrawOK struct {

	/*
	  In: Body
	*/
	Payload *models.Balance `json:"body,omitempty"`
}

// NewWithdrawOK creates WithdrawOK with default headers values
func NewWithdrawOK() *WithdrawOK {

	return &WithdrawOK{}
}

// WithPayload adds the payload to the withdraw o k response
func (o *WithdrawOK) WithPayload(payload *models.Balance) *WithdrawOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the withdraw o k response
func (o *WithdrawOK) SetPayload(payload *models.Balance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WithdrawOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WithdrawBadRequestCode is the HTTP code returned for type WithdrawBadRequest
const WithdrawBadRequestCode int = 400

/*
WithdrawBadRequest Insufficient funds or invalid request

swagger:response withdrawBadRequest
*/
type WithdrawBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWithdrawBadRequest creates WithdrawBadRequest with default headers values
func NewWithdrawBadRequest() *WithdrawBadRequest {

	return &WithdrawBadRequest{}
}

// WithPayload adds the payload to the withdraw bad request response
func (o *WithdrawBadRequest) WithPayload(payload *models.Error) *WithdrawBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the withdraw bad request response
func (o *WithdrawBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WithdrawBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
