---
swagger: "2.0"
info:
  description: "Parking Net Go project | Booking svc"
  version: "0.3.0"
  title: "parkings.booking"
tags:
  - name: "driver"
    description: "Driver operations"
  - name: "owner"
    description: "Parking owner operations"
  - name: "instruments"
    description: "Inner operations"
schemes:
  #  - "https"
  - "http"
paths:
  /booking/{booking_id}:
    get:
      tags:
        - "driver"
        - "owner"
      summary: "Get booking info by id"
      operationId: "get_booking_by_id"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Booking"
        404:
          description: "Booking not found"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]

    put:
      tags:
        - "driver"
        - "owner"
      summary: "Update booking"
      operationId: "update_booking"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to change"
          required: true
          type: "integer"
          format: "int64"
        - name: "object"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Booking"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
        400:
          description: "Incorrect data"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]

    delete:
      tags:
        - "driver"
        - "owner"
      summary: "Delete booking"
      operationId: "delete_booking"
      produces:
        - "application/json"
      parameters:
        - name: "booking_id"
          in: "path"
          description: "ID of booking to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Result"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Booking not found"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]

  /booking:
    get:
      tags:
        - "driver"
        - "owner"
      summary: "Get suitable bookings"
      operationId: "get_booking"
      produces:
        - "application/json"
      parameters:
        - name: "parking_place_id"
          in: "query"
          type: "integer"
          format: "int64"
        - name: "user_id"
          in: "query"
          type: "string"
          description: "Filter bookings by user ID (for drivers to get their own bookings)"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Booking"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Booking not found"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]
    post:
      tags:
        - "driver"
      summary: "Create booking"
      operationId: "create_booking"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "object"
          in: "body"
          required: true
          schema:
            required:
              - parking_place_id
              - date_from
              - date_to
            properties:
              parking_place_id:
                type: "integer"
                format: "int64"
              date_from:
                type: "string"
              date_to:
                type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              booking_id:
                type: "integer"
                format: "int64"
        403:
          description: "No access"
          schema:
            $ref: "#/definitions/Error"
        400:
          description: "Incorrect data"
          schema:
            $ref: "#/definitions/Error"
      security:
        - api_key: [ ]
  /metrics:
    get:
      tags:
        - "instruments"
      summary: "Prometheus metrics"
      produces:
        - "application/json"
      responses:
        200:
          description: ok

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Booking:
    type: "object"
    required:
      - "date_from"
      - "date_to"
      - "parking_place_id"
    properties:
      booking_id:
        type: "integer"
        format: "int64"
      date_from:
        type: "string"
        pattern: ^\d{2}-\d{2}-\d{4}$
        example: "31-12-2024"
      date_to:
        type: "string"
        pattern: ^\d{2}-\d{2}-\d{4}$
        example: "31-12-2025"
      parking_place_id:
        type: "integer"
        format: "int64"
      full_cost:
        type: "integer"
        format: "int64"
      status:
        type: "string"
        description: "status of booking"
        enum:
          - "Waiting"
          - "Confirmed"
          - "Canceled"
      user_id:
        type: "string"
  Error:
    type: "object"
    required:
      - "error_status_code"
    properties:
      error_message:
        type: "string"
      error_status_code:
        type: integer
  Result:
    type: "object"
    properties:
      status:
        type: "string"
      message:
        type: "string"
  ParkingPlace:
    type: "object"
    required:
      - "name"
      - "city"
      - "address"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Central Parking"
      city:
        type: "string"
        example: "Moscow"
      address:
        type: "string"
        example: "Red Square №1"
      parking_type:
        type: "string"
        description: "type of parking facility"
        enum:
          - "outdoor"
          - "covered"
          - "underground"
          - "multi-level"
      hourly_rate:
        type: "integer"
        format: "int64"
        description: "hourly parking rate"
      capacity:
        type: "integer"
        format: "int64"
        description: "total number of parking spots"
      owner_id:
        type: "string"